/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiCallback;
import ai.nexconn.ApiClient;
import ai.nexconn.ApiException;
import ai.nexconn.ApiResponse;
import ai.nexconn.Configuration;
import ai.nexconn.Pair;
import ai.nexconn.ProgressRequestBody;
import ai.nexconn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.CommunityChannelAllowedSenderListGetRequest;
import ai.nexconn.model.CommunityChannelAllowedSenderListGetResponse;
import ai.nexconn.model.CommunityChannelAllowedSenderListUpdateRequest;
import ai.nexconn.model.CommunityChannelFreezeListGetRequest;
import ai.nexconn.model.CommunityChannelFreezeListGetResponse;
import ai.nexconn.model.CommunityChannelFreezeListSetRequest;
import ai.nexconn.model.CommunityChannelMuteListAddRequest;
import ai.nexconn.model.CommunityChannelMuteListGetRequest;
import ai.nexconn.model.CommunityChannelMuteListGetResponse;
import ai.nexconn.model.CommunityChannelMuteListRemoveRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;

public class CommunityChannelModerationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CommunityChannelModerationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CommunityChannelModerationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addCommunityChannelAllowedSenderList
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addCommunityChannelAllowedSenderListCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelAllowedSenderListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/allowed-sender-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addCommunityChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelAllowedSenderListUpdateRequest' is set
        if (communityChannelAllowedSenderListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelAllowedSenderListUpdateRequest' when calling addCommunityChannelAllowedSenderList(Async)");
        }

        
        return addCommunityChannelAllowedSenderListCall(communityChannelAllowedSenderListUpdateRequest, _callback);

    }

    /**
     * Add community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse addCommunityChannelAllowedSenderList(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addCommunityChannelAllowedSenderListWithHttpInfo(communityChannelAllowedSenderListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Add community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> addCommunityChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = addCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Add community channel allowed sender list (asynchronously)
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addCommunityChannelAllowedSenderListAsync(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for addCommunityChannelMutedUsers
     * @param communityChannelMuteListAddRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addCommunityChannelMutedUsersCall(@javax.annotation.Nonnull CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelMuteListAddRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/mute-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addCommunityChannelMutedUsersValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelMuteListAddRequest' is set
        if (communityChannelMuteListAddRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelMuteListAddRequest' when calling addCommunityChannelMutedUsers(Async)");
        }

        
        return addCommunityChannelMutedUsersCall(communityChannelMuteListAddRequest, _callback);

    }

    /**
     * Add community-channel muted users
     * 
     * @param communityChannelMuteListAddRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse addCommunityChannelMutedUsers(@javax.annotation.Nonnull CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addCommunityChannelMutedUsersWithHttpInfo(communityChannelMuteListAddRequest);
        return localVarResp.getData();
    }

    /**
     * Add community-channel muted users
     * 
     * @param communityChannelMuteListAddRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> addCommunityChannelMutedUsersWithHttpInfo(@javax.annotation.Nonnull CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest) throws ApiException {
        okhttp3.Call localVarCall = addCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListAddRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Add community-channel muted users (asynchronously)
     * 
     * @param communityChannelMuteListAddRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addCommunityChannelMutedUsersAsync(@javax.annotation.Nonnull CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListAddRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getCommunityChannelFreezeList
     * @param communityChannelFreezeListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCommunityChannelFreezeListCall(@javax.annotation.Nonnull CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelFreezeListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/freeze-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getCommunityChannelFreezeListValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelFreezeListGetRequest' is set
        if (communityChannelFreezeListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelFreezeListGetRequest' when calling getCommunityChannelFreezeList(Async)");
        }

        
        return getCommunityChannelFreezeListCall(communityChannelFreezeListGetRequest, _callback);

    }

    /**
     * Get community channel freeze status
     * 
     * @param communityChannelFreezeListGetRequest  (required)
     * @return CommunityChannelFreezeListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CommunityChannelFreezeListGetResponse getCommunityChannelFreezeList(@javax.annotation.Nonnull CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest) throws ApiException {
        ApiResponse<CommunityChannelFreezeListGetResponse> localVarResp = getCommunityChannelFreezeListWithHttpInfo(communityChannelFreezeListGetRequest);
        return localVarResp.getData();
    }

    /**
     * Get community channel freeze status
     * 
     * @param communityChannelFreezeListGetRequest  (required)
     * @return ApiResponse&lt;CommunityChannelFreezeListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CommunityChannelFreezeListGetResponse> getCommunityChannelFreezeListWithHttpInfo(@javax.annotation.Nonnull CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = getCommunityChannelFreezeListValidateBeforeCall(communityChannelFreezeListGetRequest, null);
        Type localVarReturnType = new TypeToken<CommunityChannelFreezeListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Get community channel freeze status (asynchronously)
     * 
     * @param communityChannelFreezeListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCommunityChannelFreezeListAsync(@javax.annotation.Nonnull CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest, final ApiCallback<CommunityChannelFreezeListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCommunityChannelFreezeListValidateBeforeCall(communityChannelFreezeListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<CommunityChannelFreezeListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for listCommunityChannelAllowedSenderList
     * @param communityChannelAllowedSenderListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCommunityChannelAllowedSenderListCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelAllowedSenderListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/allowed-sender-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call listCommunityChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelAllowedSenderListGetRequest' is set
        if (communityChannelAllowedSenderListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelAllowedSenderListGetRequest' when calling listCommunityChannelAllowedSenderList(Async)");
        }

        
        return listCommunityChannelAllowedSenderListCall(communityChannelAllowedSenderListGetRequest, _callback);

    }

    /**
     * List community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListGetRequest  (required)
     * @return CommunityChannelAllowedSenderListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CommunityChannelAllowedSenderListGetResponse listCommunityChannelAllowedSenderList(@javax.annotation.Nonnull CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest) throws ApiException {
        ApiResponse<CommunityChannelAllowedSenderListGetResponse> localVarResp = listCommunityChannelAllowedSenderListWithHttpInfo(communityChannelAllowedSenderListGetRequest);
        return localVarResp.getData();
    }

    /**
     * List community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListGetRequest  (required)
     * @return ApiResponse&lt;CommunityChannelAllowedSenderListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CommunityChannelAllowedSenderListGetResponse> listCommunityChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = listCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListGetRequest, null);
        Type localVarReturnType = new TypeToken<CommunityChannelAllowedSenderListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * List community channel allowed sender list (asynchronously)
     * 
     * @param communityChannelAllowedSenderListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCommunityChannelAllowedSenderListAsync(@javax.annotation.Nonnull CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest, final ApiCallback<CommunityChannelAllowedSenderListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<CommunityChannelAllowedSenderListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for listCommunityChannelMutedUsers
     * @param communityChannelMuteListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCommunityChannelMutedUsersCall(@javax.annotation.Nonnull CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelMuteListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/mute-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call listCommunityChannelMutedUsersValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelMuteListGetRequest' is set
        if (communityChannelMuteListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelMuteListGetRequest' when calling listCommunityChannelMutedUsers(Async)");
        }

        
        return listCommunityChannelMutedUsersCall(communityChannelMuteListGetRequest, _callback);

    }

    /**
     * List community-channel muted users
     * 
     * @param communityChannelMuteListGetRequest  (required)
     * @return CommunityChannelMuteListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CommunityChannelMuteListGetResponse listCommunityChannelMutedUsers(@javax.annotation.Nonnull CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest) throws ApiException {
        ApiResponse<CommunityChannelMuteListGetResponse> localVarResp = listCommunityChannelMutedUsersWithHttpInfo(communityChannelMuteListGetRequest);
        return localVarResp.getData();
    }

    /**
     * List community-channel muted users
     * 
     * @param communityChannelMuteListGetRequest  (required)
     * @return ApiResponse&lt;CommunityChannelMuteListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CommunityChannelMuteListGetResponse> listCommunityChannelMutedUsersWithHttpInfo(@javax.annotation.Nonnull CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = listCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListGetRequest, null);
        Type localVarReturnType = new TypeToken<CommunityChannelMuteListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * List community-channel muted users (asynchronously)
     * 
     * @param communityChannelMuteListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCommunityChannelMutedUsersAsync(@javax.annotation.Nonnull CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest, final ApiCallback<CommunityChannelMuteListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<CommunityChannelMuteListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeCommunityChannelAllowedSenderList
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeCommunityChannelAllowedSenderListCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelAllowedSenderListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/allowed-sender-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeCommunityChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelAllowedSenderListUpdateRequest' is set
        if (communityChannelAllowedSenderListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelAllowedSenderListUpdateRequest' when calling removeCommunityChannelAllowedSenderList(Async)");
        }

        
        return removeCommunityChannelAllowedSenderListCall(communityChannelAllowedSenderListUpdateRequest, _callback);

    }

    /**
     * Remove community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse removeCommunityChannelAllowedSenderList(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeCommunityChannelAllowedSenderListWithHttpInfo(communityChannelAllowedSenderListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Remove community channel allowed sender list
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> removeCommunityChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = removeCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Remove community channel allowed sender list (asynchronously)
     * 
     * @param communityChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeCommunityChannelAllowedSenderListAsync(@javax.annotation.Nonnull CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeCommunityChannelAllowedSenderListValidateBeforeCall(communityChannelAllowedSenderListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeCommunityChannelMutedUsers
     * @param communityChannelMuteListRemoveRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeCommunityChannelMutedUsersCall(@javax.annotation.Nonnull CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelMuteListRemoveRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/mute-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeCommunityChannelMutedUsersValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelMuteListRemoveRequest' is set
        if (communityChannelMuteListRemoveRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelMuteListRemoveRequest' when calling removeCommunityChannelMutedUsers(Async)");
        }

        
        return removeCommunityChannelMutedUsersCall(communityChannelMuteListRemoveRequest, _callback);

    }

    /**
     * Remove community-channel muted users
     * 
     * @param communityChannelMuteListRemoveRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse removeCommunityChannelMutedUsers(@javax.annotation.Nonnull CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeCommunityChannelMutedUsersWithHttpInfo(communityChannelMuteListRemoveRequest);
        return localVarResp.getData();
    }

    /**
     * Remove community-channel muted users
     * 
     * @param communityChannelMuteListRemoveRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> removeCommunityChannelMutedUsersWithHttpInfo(@javax.annotation.Nonnull CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest) throws ApiException {
        okhttp3.Call localVarCall = removeCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListRemoveRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Remove community-channel muted users (asynchronously)
     * 
     * @param communityChannelMuteListRemoveRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeCommunityChannelMutedUsersAsync(@javax.annotation.Nonnull CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeCommunityChannelMutedUsersValidateBeforeCall(communityChannelMuteListRemoveRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for setCommunityChannelFreezeList
     * @param communityChannelFreezeListSetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setCommunityChannelFreezeListCall(@javax.annotation.Nonnull CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = communityChannelFreezeListSetRequest;
                // create path and map variables
        String localVarPath = "/v4/community-channel/freeze-list/set";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call setCommunityChannelFreezeListValidateBeforeCall(@javax.annotation.Nonnull CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'communityChannelFreezeListSetRequest' is set
        if (communityChannelFreezeListSetRequest == null) {
            throw new ApiException("Missing the required parameter 'communityChannelFreezeListSetRequest' when calling setCommunityChannelFreezeList(Async)");
        }

        
        return setCommunityChannelFreezeListCall(communityChannelFreezeListSetRequest, _callback);

    }

    /**
     * Set community channel freeze list
     * 
     * @param communityChannelFreezeListSetRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse setCommunityChannelFreezeList(@javax.annotation.Nonnull CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = setCommunityChannelFreezeListWithHttpInfo(communityChannelFreezeListSetRequest);
        return localVarResp.getData();
    }

    /**
     * Set community channel freeze list
     * 
     * @param communityChannelFreezeListSetRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> setCommunityChannelFreezeListWithHttpInfo(@javax.annotation.Nonnull CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest) throws ApiException {
        okhttp3.Call localVarCall = setCommunityChannelFreezeListValidateBeforeCall(communityChannelFreezeListSetRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Set community channel freeze list (asynchronously)
     * 
     * @param communityChannelFreezeListSetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setCommunityChannelFreezeListAsync(@javax.annotation.Nonnull CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = setCommunityChannelFreezeListValidateBeforeCall(communityChannelFreezeListSetRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    }
