/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiCallback;
import ai.nexconn.ApiClient;
import ai.nexconn.ApiException;
import ai.nexconn.ApiResponse;
import ai.nexconn.Configuration;
import ai.nexconn.Pair;
import ai.nexconn.ProgressRequestBody;
import ai.nexconn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.GroupChannelAllowedSenderListGetRequest;
import ai.nexconn.model.GroupChannelAllowedSenderListGetResponse;
import ai.nexconn.model.GroupChannelAllowedSenderListUpdateRequest;
import ai.nexconn.model.GroupChannelFreezeListGetRequest;
import ai.nexconn.model.GroupChannelFreezeListGetResponse;
import ai.nexconn.model.GroupChannelFreezeListUpdateRequest;
import ai.nexconn.model.GroupChannelUserMuteListAddRequest;
import ai.nexconn.model.GroupChannelUserMuteListGetRequest;
import ai.nexconn.model.GroupChannelUserMuteListGetResponse;
import ai.nexconn.model.GroupChannelUserMuteListRemoveRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;

public class GroupChannelModerationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GroupChannelModerationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GroupChannelModerationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addGroupChannelAllowedSenderList
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/add-to-group-ban-whitelist">Add to allowed senders list Documentation</a>
     */
    public okhttp3.Call addGroupChannelAllowedSenderListCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelAllowedSenderListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/allowed-sender-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addGroupChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelAllowedSenderListUpdateRequest' is set
        if (groupChannelAllowedSenderListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelAllowedSenderListUpdateRequest' when calling addGroupChannelAllowedSenderList(Async)");
        }

        
        return addGroupChannelAllowedSenderListCall(groupChannelAllowedSenderListUpdateRequest, _callback);

    }

    /**
     * Add to allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/add-to-group-ban-whitelist">Add to allowed senders list Documentation</a>
     */
    public CodeOnlyResponse addGroupChannelAllowedSenderList(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addGroupChannelAllowedSenderListWithHttpInfo(groupChannelAllowedSenderListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Add to allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/add-to-group-ban-whitelist">Add to allowed senders list Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> addGroupChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = addGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Add to allowed senders list (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/add-to-group-ban-whitelist">Add to allowed senders list Documentation</a>
     */
    public okhttp3.Call addGroupChannelAllowedSenderListAsync(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for addGroupChannelFreezeList
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ban-group">Freeze a group Documentation</a>
     */
    public okhttp3.Call addGroupChannelFreezeListCall(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelFreezeListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/freeze-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addGroupChannelFreezeListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelFreezeListUpdateRequest' is set
        if (groupChannelFreezeListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelFreezeListUpdateRequest' when calling addGroupChannelFreezeList(Async)");
        }

        
        return addGroupChannelFreezeListCall(groupChannelFreezeListUpdateRequest, _callback);

    }

    /**
     * Freeze a group
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ban-group">Freeze a group Documentation</a>
     */
    public CodeOnlyResponse addGroupChannelFreezeList(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addGroupChannelFreezeListWithHttpInfo(groupChannelFreezeListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Freeze a group
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ban-group">Freeze a group Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> addGroupChannelFreezeListWithHttpInfo(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = addGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Freeze a group (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ban-group">Freeze a group Documentation</a>
     */
    public okhttp3.Call addGroupChannelFreezeListAsync(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for addGroupChannelUserMuteList
     * @param groupChannelUserMuteListAddRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/gag-user">Mute a group member Documentation</a>
     */
    public okhttp3.Call addGroupChannelUserMuteListCall(@javax.annotation.Nonnull GroupChannelUserMuteListAddRequest groupChannelUserMuteListAddRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelUserMuteListAddRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/user/mute-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addGroupChannelUserMuteListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelUserMuteListAddRequest groupChannelUserMuteListAddRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelUserMuteListAddRequest' is set
        if (groupChannelUserMuteListAddRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelUserMuteListAddRequest' when calling addGroupChannelUserMuteList(Async)");
        }

        
        return addGroupChannelUserMuteListCall(groupChannelUserMuteListAddRequest, _callback);

    }

    /**
     * Mute a group member
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListAddRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/gag-user">Mute a group member Documentation</a>
     */
    public CodeOnlyResponse addGroupChannelUserMuteList(@javax.annotation.Nonnull GroupChannelUserMuteListAddRequest groupChannelUserMuteListAddRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addGroupChannelUserMuteListWithHttpInfo(groupChannelUserMuteListAddRequest);
        return localVarResp.getData();
    }

    /**
     * Mute a group member
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListAddRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/gag-user">Mute a group member Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> addGroupChannelUserMuteListWithHttpInfo(@javax.annotation.Nonnull GroupChannelUserMuteListAddRequest groupChannelUserMuteListAddRequest) throws ApiException {
        okhttp3.Call localVarCall = addGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListAddRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Mute a group member (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListAddRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/gag-user">Mute a group member Documentation</a>
     */
    public okhttp3.Call addGroupChannelUserMuteListAsync(@javax.annotation.Nonnull GroupChannelUserMuteListAddRequest groupChannelUserMuteListAddRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListAddRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getGroupChannelAllowedSenderList
     * @param groupChannelAllowedSenderListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-group-ban-whitelist">Query allowed senders list Documentation</a>
     */
    public okhttp3.Call getGroupChannelAllowedSenderListCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListGetRequest groupChannelAllowedSenderListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelAllowedSenderListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/allowed-sender-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getGroupChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListGetRequest groupChannelAllowedSenderListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelAllowedSenderListGetRequest' is set
        if (groupChannelAllowedSenderListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelAllowedSenderListGetRequest' when calling getGroupChannelAllowedSenderList(Async)");
        }

        
        return getGroupChannelAllowedSenderListCall(groupChannelAllowedSenderListGetRequest, _callback);

    }

    /**
     * Query allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListGetRequest  (required)
     * @return GroupChannelAllowedSenderListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-group-ban-whitelist">Query allowed senders list Documentation</a>
     */
    public GroupChannelAllowedSenderListGetResponse getGroupChannelAllowedSenderList(@javax.annotation.Nonnull GroupChannelAllowedSenderListGetRequest groupChannelAllowedSenderListGetRequest) throws ApiException {
        ApiResponse<GroupChannelAllowedSenderListGetResponse> localVarResp = getGroupChannelAllowedSenderListWithHttpInfo(groupChannelAllowedSenderListGetRequest);
        return localVarResp.getData();
    }

    /**
     * Query allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListGetRequest  (required)
     * @return ApiResponse&lt;GroupChannelAllowedSenderListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-group-ban-whitelist">Query allowed senders list Documentation</a>
     */
    public ApiResponse<GroupChannelAllowedSenderListGetResponse> getGroupChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull GroupChannelAllowedSenderListGetRequest groupChannelAllowedSenderListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = getGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListGetRequest, null);
        Type localVarReturnType = new TypeToken<GroupChannelAllowedSenderListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Query allowed senders list (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-group-ban-whitelist">Query allowed senders list Documentation</a>
     */
    public okhttp3.Call getGroupChannelAllowedSenderListAsync(@javax.annotation.Nonnull GroupChannelAllowedSenderListGetRequest groupChannelAllowedSenderListGetRequest, final ApiCallback<GroupChannelAllowedSenderListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<GroupChannelAllowedSenderListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getGroupChannelFreezeList
     * @param groupChannelFreezeListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-banned-state-or-list">Query group freeze status Documentation</a>
     */
    public okhttp3.Call getGroupChannelFreezeListCall(@javax.annotation.Nonnull GroupChannelFreezeListGetRequest groupChannelFreezeListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelFreezeListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/freeze-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getGroupChannelFreezeListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelFreezeListGetRequest groupChannelFreezeListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelFreezeListGetRequest' is set
        if (groupChannelFreezeListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelFreezeListGetRequest' when calling getGroupChannelFreezeList(Async)");
        }

        
        return getGroupChannelFreezeListCall(groupChannelFreezeListGetRequest, _callback);

    }

    /**
     * Query group freeze status
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListGetRequest  (required)
     * @return GroupChannelFreezeListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-banned-state-or-list">Query group freeze status Documentation</a>
     */
    public GroupChannelFreezeListGetResponse getGroupChannelFreezeList(@javax.annotation.Nonnull GroupChannelFreezeListGetRequest groupChannelFreezeListGetRequest) throws ApiException {
        ApiResponse<GroupChannelFreezeListGetResponse> localVarResp = getGroupChannelFreezeListWithHttpInfo(groupChannelFreezeListGetRequest);
        return localVarResp.getData();
    }

    /**
     * Query group freeze status
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListGetRequest  (required)
     * @return ApiResponse&lt;GroupChannelFreezeListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-banned-state-or-list">Query group freeze status Documentation</a>
     */
    public ApiResponse<GroupChannelFreezeListGetResponse> getGroupChannelFreezeListWithHttpInfo(@javax.annotation.Nonnull GroupChannelFreezeListGetRequest groupChannelFreezeListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = getGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListGetRequest, null);
        Type localVarReturnType = new TypeToken<GroupChannelFreezeListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Query group freeze status (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-banned-state-or-list">Query group freeze status Documentation</a>
     */
    public okhttp3.Call getGroupChannelFreezeListAsync(@javax.annotation.Nonnull GroupChannelFreezeListGetRequest groupChannelFreezeListGetRequest, final ApiCallback<GroupChannelFreezeListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<GroupChannelFreezeListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getGroupChannelUserMuteList
     * @param groupChannelUserMuteListGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-gagged-user">List muted group members Documentation</a>
     */
    public okhttp3.Call getGroupChannelUserMuteListCall(@javax.annotation.Nonnull GroupChannelUserMuteListGetRequest groupChannelUserMuteListGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelUserMuteListGetRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/user/mute-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getGroupChannelUserMuteListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelUserMuteListGetRequest groupChannelUserMuteListGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelUserMuteListGetRequest' is set
        if (groupChannelUserMuteListGetRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelUserMuteListGetRequest' when calling getGroupChannelUserMuteList(Async)");
        }

        
        return getGroupChannelUserMuteListCall(groupChannelUserMuteListGetRequest, _callback);

    }

    /**
     * List muted group members
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/group-channel/user/mute-list-get&#x60;.
     * @param groupChannelUserMuteListGetRequest  (required)
     * @return GroupChannelUserMuteListGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-gagged-user">List muted group members Documentation</a>
     */
    public GroupChannelUserMuteListGetResponse getGroupChannelUserMuteList(@javax.annotation.Nonnull GroupChannelUserMuteListGetRequest groupChannelUserMuteListGetRequest) throws ApiException {
        ApiResponse<GroupChannelUserMuteListGetResponse> localVarResp = getGroupChannelUserMuteListWithHttpInfo(groupChannelUserMuteListGetRequest);
        return localVarResp.getData();
    }

    /**
     * List muted group members
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/group-channel/user/mute-list-get&#x60;.
     * @param groupChannelUserMuteListGetRequest  (required)
     * @return ApiResponse&lt;GroupChannelUserMuteListGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-gagged-user">List muted group members Documentation</a>
     */
    public ApiResponse<GroupChannelUserMuteListGetResponse> getGroupChannelUserMuteListWithHttpInfo(@javax.annotation.Nonnull GroupChannelUserMuteListGetRequest groupChannelUserMuteListGetRequest) throws ApiException {
        okhttp3.Call localVarCall = getGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListGetRequest, null);
        Type localVarReturnType = new TypeToken<GroupChannelUserMuteListGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * List muted group members (asynchronously)
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/group-channel/user/mute-list-get&#x60;.
     * @param groupChannelUserMuteListGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/query-gagged-user">List muted group members Documentation</a>
     */
    public okhttp3.Call getGroupChannelUserMuteListAsync(@javax.annotation.Nonnull GroupChannelUserMuteListGetRequest groupChannelUserMuteListGetRequest, final ApiCallback<GroupChannelUserMuteListGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListGetRequest, _callback);
        Type localVarReturnType = new TypeToken<GroupChannelUserMuteListGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeGroupChannelAllowedSenderList
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/remove-from-group-ban-whitelist">Remove from allowed senders list Documentation</a>
     */
    public okhttp3.Call removeGroupChannelAllowedSenderListCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelAllowedSenderListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/allowed-sender-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeGroupChannelAllowedSenderListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelAllowedSenderListUpdateRequest' is set
        if (groupChannelAllowedSenderListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelAllowedSenderListUpdateRequest' when calling removeGroupChannelAllowedSenderList(Async)");
        }

        
        return removeGroupChannelAllowedSenderListCall(groupChannelAllowedSenderListUpdateRequest, _callback);

    }

    /**
     * Remove from allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/remove-from-group-ban-whitelist">Remove from allowed senders list Documentation</a>
     */
    public CodeOnlyResponse removeGroupChannelAllowedSenderList(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeGroupChannelAllowedSenderListWithHttpInfo(groupChannelAllowedSenderListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Remove from allowed senders list
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/remove-from-group-ban-whitelist">Remove from allowed senders list Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> removeGroupChannelAllowedSenderListWithHttpInfo(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = removeGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Remove from allowed senders list (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelAllowedSenderListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/remove-from-group-ban-whitelist">Remove from allowed senders list Documentation</a>
     */
    public okhttp3.Call removeGroupChannelAllowedSenderListAsync(@javax.annotation.Nonnull GroupChannelAllowedSenderListUpdateRequest groupChannelAllowedSenderListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeGroupChannelAllowedSenderListValidateBeforeCall(groupChannelAllowedSenderListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeGroupChannelFreezeList
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/unban-group">Unfreeze a group Documentation</a>
     */
    public okhttp3.Call removeGroupChannelFreezeListCall(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelFreezeListUpdateRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/freeze-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeGroupChannelFreezeListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelFreezeListUpdateRequest' is set
        if (groupChannelFreezeListUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelFreezeListUpdateRequest' when calling removeGroupChannelFreezeList(Async)");
        }

        
        return removeGroupChannelFreezeListCall(groupChannelFreezeListUpdateRequest, _callback);

    }

    /**
     * Unfreeze a group
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/unban-group">Unfreeze a group Documentation</a>
     */
    public CodeOnlyResponse removeGroupChannelFreezeList(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeGroupChannelFreezeListWithHttpInfo(groupChannelFreezeListUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Unfreeze a group
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/unban-group">Unfreeze a group Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> removeGroupChannelFreezeListWithHttpInfo(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = removeGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListUpdateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Unfreeze a group (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelFreezeListUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/unban-group">Unfreeze a group Documentation</a>
     */
    public okhttp3.Call removeGroupChannelFreezeListAsync(@javax.annotation.Nonnull GroupChannelFreezeListUpdateRequest groupChannelFreezeListUpdateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeGroupChannelFreezeListValidateBeforeCall(groupChannelFreezeListUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeGroupChannelUserMuteList
     * @param groupChannelUserMuteListRemoveRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ungag-user">Unmute a group member Documentation</a>
     */
    public okhttp3.Call removeGroupChannelUserMuteListCall(@javax.annotation.Nonnull GroupChannelUserMuteListRemoveRequest groupChannelUserMuteListRemoveRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = groupChannelUserMuteListRemoveRequest;
                // create path and map variables
        String localVarPath = "/v4/group-channel/user/mute-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeGroupChannelUserMuteListValidateBeforeCall(@javax.annotation.Nonnull GroupChannelUserMuteListRemoveRequest groupChannelUserMuteListRemoveRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'groupChannelUserMuteListRemoveRequest' is set
        if (groupChannelUserMuteListRemoveRequest == null) {
            throw new ApiException("Missing the required parameter 'groupChannelUserMuteListRemoveRequest' when calling removeGroupChannelUserMuteList(Async)");
        }

        
        return removeGroupChannelUserMuteListCall(groupChannelUserMuteListRemoveRequest, _callback);

    }

    /**
     * Unmute a group member
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListRemoveRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ungag-user">Unmute a group member Documentation</a>
     */
    public CodeOnlyResponse removeGroupChannelUserMuteList(@javax.annotation.Nonnull GroupChannelUserMuteListRemoveRequest groupChannelUserMuteListRemoveRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeGroupChannelUserMuteListWithHttpInfo(groupChannelUserMuteListRemoveRequest);
        return localVarResp.getData();
    }

    /**
     * Unmute a group member
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListRemoveRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ungag-user">Unmute a group member Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> removeGroupChannelUserMuteListWithHttpInfo(@javax.annotation.Nonnull GroupChannelUserMuteListRemoveRequest groupChannelUserMuteListRemoveRequest) throws ApiException {
        okhttp3.Call localVarCall = removeGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListRemoveRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Unmute a group member (asynchronously)
     * Rate limit: 100/sec.
     * @param groupChannelUserMuteListRemoveRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/group-channel/mute/ungag-user">Unmute a group member Documentation</a>
     */
    public okhttp3.Call removeGroupChannelUserMuteListAsync(@javax.annotation.Nonnull GroupChannelUserMuteListRemoveRequest groupChannelUserMuteListRemoveRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeGroupChannelUserMuteListValidateBeforeCall(groupChannelUserMuteListRemoveRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    }
