/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiCallback;
import ai.nexconn.ApiClient;
import ai.nexconn.ApiException;
import ai.nexconn.ApiResponse;
import ai.nexconn.Configuration;
import ai.nexconn.Pair;
import ai.nexconn.ProgressRequestBody;
import ai.nexconn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.ProfanityWordBatchAddRequest;
import ai.nexconn.model.ProfanityWordBatchAddResponse;
import ai.nexconn.model.ProfanityWordBatchDeleteRequest;
import ai.nexconn.model.ProfanityWordDeleteRequest;
import ai.nexconn.model.ProfanityWordListRequest;
import ai.nexconn.model.ProfanityWordListResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;

public class ModerationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ModerationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ModerationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for batchAddProfanityWords
     * @param profanityWordBatchAddRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchAddProfanityWordsCall(@javax.annotation.Nonnull ProfanityWordBatchAddRequest profanityWordBatchAddRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = profanityWordBatchAddRequest;
                // create path and map variables
        String localVarPath = "/v4/profanity-word/batch/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call batchAddProfanityWordsValidateBeforeCall(@javax.annotation.Nonnull ProfanityWordBatchAddRequest profanityWordBatchAddRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'profanityWordBatchAddRequest' is set
        if (profanityWordBatchAddRequest == null) {
            throw new ApiException("Missing the required parameter 'profanityWordBatchAddRequest' when calling batchAddProfanityWords(Async)");
        }

        
        return batchAddProfanityWordsCall(profanityWordBatchAddRequest, _callback);

    }

    /**
     * Batch add profanity words
     * 
     * @param profanityWordBatchAddRequest  (required)
     * @return ProfanityWordBatchAddResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ProfanityWordBatchAddResponse batchAddProfanityWords(@javax.annotation.Nonnull ProfanityWordBatchAddRequest profanityWordBatchAddRequest) throws ApiException {
        ApiResponse<ProfanityWordBatchAddResponse> localVarResp = batchAddProfanityWordsWithHttpInfo(profanityWordBatchAddRequest);
        return localVarResp.getData();
    }

    /**
     * Batch add profanity words
     * 
     * @param profanityWordBatchAddRequest  (required)
     * @return ApiResponse&lt;ProfanityWordBatchAddResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProfanityWordBatchAddResponse> batchAddProfanityWordsWithHttpInfo(@javax.annotation.Nonnull ProfanityWordBatchAddRequest profanityWordBatchAddRequest) throws ApiException {
        okhttp3.Call localVarCall = batchAddProfanityWordsValidateBeforeCall(profanityWordBatchAddRequest, null);
        Type localVarReturnType = new TypeToken<ProfanityWordBatchAddResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Batch add profanity words (asynchronously)
     * 
     * @param profanityWordBatchAddRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchAddProfanityWordsAsync(@javax.annotation.Nonnull ProfanityWordBatchAddRequest profanityWordBatchAddRequest, final ApiCallback<ProfanityWordBatchAddResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchAddProfanityWordsValidateBeforeCall(profanityWordBatchAddRequest, _callback);
        Type localVarReturnType = new TypeToken<ProfanityWordBatchAddResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for batchRemoveProfanityWords
     * @param profanityWordBatchDeleteRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchRemoveProfanityWordsCall(@javax.annotation.Nonnull ProfanityWordBatchDeleteRequest profanityWordBatchDeleteRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = profanityWordBatchDeleteRequest;
                // create path and map variables
        String localVarPath = "/v4/profanity-word/batch/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call batchRemoveProfanityWordsValidateBeforeCall(@javax.annotation.Nonnull ProfanityWordBatchDeleteRequest profanityWordBatchDeleteRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'profanityWordBatchDeleteRequest' is set
        if (profanityWordBatchDeleteRequest == null) {
            throw new ApiException("Missing the required parameter 'profanityWordBatchDeleteRequest' when calling batchRemoveProfanityWords(Async)");
        }

        
        return batchRemoveProfanityWordsCall(profanityWordBatchDeleteRequest, _callback);

    }

    /**
     * Batch delete profanity words
     * 
     * @param profanityWordBatchDeleteRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse batchRemoveProfanityWords(@javax.annotation.Nonnull ProfanityWordBatchDeleteRequest profanityWordBatchDeleteRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = batchRemoveProfanityWordsWithHttpInfo(profanityWordBatchDeleteRequest);
        return localVarResp.getData();
    }

    /**
     * Batch delete profanity words
     * 
     * @param profanityWordBatchDeleteRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> batchRemoveProfanityWordsWithHttpInfo(@javax.annotation.Nonnull ProfanityWordBatchDeleteRequest profanityWordBatchDeleteRequest) throws ApiException {
        okhttp3.Call localVarCall = batchRemoveProfanityWordsValidateBeforeCall(profanityWordBatchDeleteRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Batch delete profanity words (asynchronously)
     * 
     * @param profanityWordBatchDeleteRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchRemoveProfanityWordsAsync(@javax.annotation.Nonnull ProfanityWordBatchDeleteRequest profanityWordBatchDeleteRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchRemoveProfanityWordsValidateBeforeCall(profanityWordBatchDeleteRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for listProfanityWords
     * @param profanityWordListRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listProfanityWordsCall(@javax.annotation.Nonnull ProfanityWordListRequest profanityWordListRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = profanityWordListRequest;
                // create path and map variables
        String localVarPath = "/v4/profanity-word/list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call listProfanityWordsValidateBeforeCall(@javax.annotation.Nonnull ProfanityWordListRequest profanityWordListRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'profanityWordListRequest' is set
        if (profanityWordListRequest == null) {
            throw new ApiException("Missing the required parameter 'profanityWordListRequest' when calling listProfanityWords(Async)");
        }

        
        return listProfanityWordsCall(profanityWordListRequest, _callback);

    }

    /**
     * List profanity words
     * 
     * @param profanityWordListRequest  (required)
     * @return ProfanityWordListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ProfanityWordListResponse listProfanityWords(@javax.annotation.Nonnull ProfanityWordListRequest profanityWordListRequest) throws ApiException {
        ApiResponse<ProfanityWordListResponse> localVarResp = listProfanityWordsWithHttpInfo(profanityWordListRequest);
        return localVarResp.getData();
    }

    /**
     * List profanity words
     * 
     * @param profanityWordListRequest  (required)
     * @return ApiResponse&lt;ProfanityWordListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProfanityWordListResponse> listProfanityWordsWithHttpInfo(@javax.annotation.Nonnull ProfanityWordListRequest profanityWordListRequest) throws ApiException {
        okhttp3.Call localVarCall = listProfanityWordsValidateBeforeCall(profanityWordListRequest, null);
        Type localVarReturnType = new TypeToken<ProfanityWordListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * List profanity words (asynchronously)
     * 
     * @param profanityWordListRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listProfanityWordsAsync(@javax.annotation.Nonnull ProfanityWordListRequest profanityWordListRequest, final ApiCallback<ProfanityWordListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listProfanityWordsValidateBeforeCall(profanityWordListRequest, _callback);
        Type localVarReturnType = new TypeToken<ProfanityWordListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for removeProfanityWord
     * @param profanityWordDeleteRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeProfanityWordCall(@javax.annotation.Nonnull ProfanityWordDeleteRequest profanityWordDeleteRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = profanityWordDeleteRequest;
                // create path and map variables
        String localVarPath = "/v4/profanity-word/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeProfanityWordValidateBeforeCall(@javax.annotation.Nonnull ProfanityWordDeleteRequest profanityWordDeleteRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'profanityWordDeleteRequest' is set
        if (profanityWordDeleteRequest == null) {
            throw new ApiException("Missing the required parameter 'profanityWordDeleteRequest' when calling removeProfanityWord(Async)");
        }

        
        return removeProfanityWordCall(profanityWordDeleteRequest, _callback);

    }

    /**
     * Delete profanity word
     * 
     * @param profanityWordDeleteRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public CodeOnlyResponse removeProfanityWord(@javax.annotation.Nonnull ProfanityWordDeleteRequest profanityWordDeleteRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeProfanityWordWithHttpInfo(profanityWordDeleteRequest);
        return localVarResp.getData();
    }

    /**
     * Delete profanity word
     * 
     * @param profanityWordDeleteRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CodeOnlyResponse> removeProfanityWordWithHttpInfo(@javax.annotation.Nonnull ProfanityWordDeleteRequest profanityWordDeleteRequest) throws ApiException {
        okhttp3.Call localVarCall = removeProfanityWordValidateBeforeCall(profanityWordDeleteRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Delete profanity word (asynchronously)
     * 
     * @param profanityWordDeleteRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeProfanityWordAsync(@javax.annotation.Nonnull ProfanityWordDeleteRequest profanityWordDeleteRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeProfanityWordValidateBeforeCall(profanityWordDeleteRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    }
