/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiCallback;
import ai.nexconn.ApiClient;
import ai.nexconn.ApiException;
import ai.nexconn.ApiResponse;
import ai.nexconn.Configuration;
import ai.nexconn.Pair;
import ai.nexconn.ProgressRequestBody;
import ai.nexconn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.OpenChannelLowPriorityMessageTypeListRequest;
import ai.nexconn.model.OpenChannelMessageTypeListResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;

public class OpenChannelMessagePriorityApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OpenChannelMessagePriorityApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OpenChannelMessagePriorityApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addOpenChannelLowPriorityMessageTypeList
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/add-low-priority-message-type">Add low-priority message types Documentation</a>
     */
    public okhttp3.Call addOpenChannelLowPriorityMessageTypeListCall(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelLowPriorityMessageTypeListRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/low-priority-message-type-list/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call addOpenChannelLowPriorityMessageTypeListValidateBeforeCall(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelLowPriorityMessageTypeListRequest' is set
        if (openChannelLowPriorityMessageTypeListRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelLowPriorityMessageTypeListRequest' when calling addOpenChannelLowPriorityMessageTypeList(Async)");
        }

        
        return addOpenChannelLowPriorityMessageTypeListCall(openChannelLowPriorityMessageTypeListRequest, _callback);

    }

    /**
     * Add low-priority message types
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/add-low-priority-message-type">Add low-priority message types Documentation</a>
     */
    public CodeOnlyResponse addOpenChannelLowPriorityMessageTypeList(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = addOpenChannelLowPriorityMessageTypeListWithHttpInfo(openChannelLowPriorityMessageTypeListRequest);
        return localVarResp.getData();
    }

    /**
     * Add low-priority message types
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/add-low-priority-message-type">Add low-priority message types Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> addOpenChannelLowPriorityMessageTypeListWithHttpInfo(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest) throws ApiException {
        okhttp3.Call localVarCall = addOpenChannelLowPriorityMessageTypeListValidateBeforeCall(openChannelLowPriorityMessageTypeListRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Add low-priority message types (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/add-low-priority-message-type">Add low-priority message types Documentation</a>
     */
    public okhttp3.Call addOpenChannelLowPriorityMessageTypeListAsync(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addOpenChannelLowPriorityMessageTypeListValidateBeforeCall(openChannelLowPriorityMessageTypeListRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getOpenChannelLowPriorityMessageTypeList
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/query-low-priority-message-type">Query low-priority message types Documentation</a>
     */
    public okhttp3.Call getOpenChannelLowPriorityMessageTypeListCall(@javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = Collections.emptyMap();
        if (body != null) {
            localVarPostBody = body;
        }
        // create path and map variables
        String localVarPath = "/v4/open-channel/low-priority-message-type-list/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    public okhttp3.Call getOpenChannelLowPriorityMessageTypeListCall(final ApiCallback _callback) throws ApiException {
        return getOpenChannelLowPriorityMessageTypeListCall(Collections.emptyMap(), _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getOpenChannelLowPriorityMessageTypeListValidateBeforeCall(@javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        
        return getOpenChannelLowPriorityMessageTypeListCall(body, _callback);

    }

    /**
     * Query low-priority message types
     * Rate limit: 100/sec.
     * @param body  (required)
     * @return OpenChannelMessageTypeListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/query-low-priority-message-type">Query low-priority message types Documentation</a>
     */
    public OpenChannelMessageTypeListResponse getOpenChannelLowPriorityMessageTypeList(@javax.annotation.Nonnull Object body) throws ApiException {
        ApiResponse<OpenChannelMessageTypeListResponse> localVarResp = getOpenChannelLowPriorityMessageTypeListWithHttpInfo(body);
        return localVarResp.getData();
    }
    public OpenChannelMessageTypeListResponse getOpenChannelLowPriorityMessageTypeList() throws ApiException {
        return getOpenChannelLowPriorityMessageTypeList(Collections.emptyMap());
    }

    /**
     * Query low-priority message types
     * Rate limit: 100/sec.
     * @param body  (required)
     * @return ApiResponse&lt;OpenChannelMessageTypeListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/query-low-priority-message-type">Query low-priority message types Documentation</a>
     */
    public ApiResponse<OpenChannelMessageTypeListResponse> getOpenChannelLowPriorityMessageTypeListWithHttpInfo(@javax.annotation.Nonnull Object body) throws ApiException {
        okhttp3.Call localVarCall = getOpenChannelLowPriorityMessageTypeListValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<OpenChannelMessageTypeListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    
    public ApiResponse<OpenChannelMessageTypeListResponse> getOpenChannelLowPriorityMessageTypeListWithHttpInfo() throws ApiException {
        return getOpenChannelLowPriorityMessageTypeListWithHttpInfo(Collections.emptyMap());
    }
    

    /**
     * Query low-priority message types (asynchronously)
     * Rate limit: 100/sec.
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/query-low-priority-message-type">Query low-priority message types Documentation</a>
     */
    public okhttp3.Call getOpenChannelLowPriorityMessageTypeListAsync(@javax.annotation.Nonnull Object body, final ApiCallback<OpenChannelMessageTypeListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOpenChannelLowPriorityMessageTypeListValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<OpenChannelMessageTypeListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    public okhttp3.Call getOpenChannelLowPriorityMessageTypeListAsync(final ApiCallback<OpenChannelMessageTypeListResponse> _callback) throws ApiException {
        return getOpenChannelLowPriorityMessageTypeListAsync(Collections.emptyMap(), _callback);
    }

        /**
     * Build call for removeOpenChannelLowPriorityMessageTypeList
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/remove-low-priority-message-type">Remove low-priority message types Documentation</a>
     */
    public okhttp3.Call removeOpenChannelLowPriorityMessageTypeListCall(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelLowPriorityMessageTypeListRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/low-priority-message-type-list/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call removeOpenChannelLowPriorityMessageTypeListValidateBeforeCall(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelLowPriorityMessageTypeListRequest' is set
        if (openChannelLowPriorityMessageTypeListRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelLowPriorityMessageTypeListRequest' when calling removeOpenChannelLowPriorityMessageTypeList(Async)");
        }

        
        return removeOpenChannelLowPriorityMessageTypeListCall(openChannelLowPriorityMessageTypeListRequest, _callback);

    }

    /**
     * Remove low-priority message types
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/remove-low-priority-message-type">Remove low-priority message types Documentation</a>
     */
    public CodeOnlyResponse removeOpenChannelLowPriorityMessageTypeList(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = removeOpenChannelLowPriorityMessageTypeListWithHttpInfo(openChannelLowPriorityMessageTypeListRequest);
        return localVarResp.getData();
    }

    /**
     * Remove low-priority message types
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/remove-low-priority-message-type">Remove low-priority message types Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> removeOpenChannelLowPriorityMessageTypeListWithHttpInfo(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest) throws ApiException {
        okhttp3.Call localVarCall = removeOpenChannelLowPriorityMessageTypeListValidateBeforeCall(openChannelLowPriorityMessageTypeListRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Remove low-priority message types (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelLowPriorityMessageTypeListRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/message-priority/remove-low-priority-message-type">Remove low-priority message types Documentation</a>
     */
    public okhttp3.Call removeOpenChannelLowPriorityMessageTypeListAsync(@javax.annotation.Nonnull OpenChannelLowPriorityMessageTypeListRequest openChannelLowPriorityMessageTypeListRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeOpenChannelLowPriorityMessageTypeListValidateBeforeCall(openChannelLowPriorityMessageTypeListRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    }
