/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiCallback;
import ai.nexconn.ApiClient;
import ai.nexconn.ApiException;
import ai.nexconn.ApiResponse;
import ai.nexconn.Configuration;
import ai.nexconn.Pair;
import ai.nexconn.ProgressRequestBody;
import ai.nexconn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.OpenChannelCreateRequest;
import ai.nexconn.model.OpenChannelDestroyRequest;
import ai.nexconn.model.OpenChannelDestroyTypeSetRequest;
import ai.nexconn.model.OpenChannelGetRequest;
import ai.nexconn.model.OpenChannelGetResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;

public class OpenChannelManagementApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OpenChannelManagementApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OpenChannelManagementApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createOpenChannel
     * @param openChannelCreateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/create">Create an open channel Documentation</a>
     */
    public okhttp3.Call createOpenChannelCall(@javax.annotation.Nonnull OpenChannelCreateRequest openChannelCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelCreateRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/create";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call createOpenChannelValidateBeforeCall(@javax.annotation.Nonnull OpenChannelCreateRequest openChannelCreateRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelCreateRequest' is set
        if (openChannelCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelCreateRequest' when calling createOpenChannel(Async)");
        }

        
        return createOpenChannelCall(openChannelCreateRequest, _callback);

    }

    /**
     * Create an open channel
     * Rate limit: 100/sec.
     * @param openChannelCreateRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/create">Create an open channel Documentation</a>
     */
    public CodeOnlyResponse createOpenChannel(@javax.annotation.Nonnull OpenChannelCreateRequest openChannelCreateRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = createOpenChannelWithHttpInfo(openChannelCreateRequest);
        return localVarResp.getData();
    }

    /**
     * Create an open channel
     * Rate limit: 100/sec.
     * @param openChannelCreateRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/create">Create an open channel Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> createOpenChannelWithHttpInfo(@javax.annotation.Nonnull OpenChannelCreateRequest openChannelCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = createOpenChannelValidateBeforeCall(openChannelCreateRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Create an open channel (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelCreateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/create">Create an open channel Documentation</a>
     */
    public okhttp3.Call createOpenChannelAsync(@javax.annotation.Nonnull OpenChannelCreateRequest openChannelCreateRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createOpenChannelValidateBeforeCall(openChannelCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for destroyOpenChannels
     * @param openChannelDestroyRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/destroy">Destroy an open channel Documentation</a>
     */
    public okhttp3.Call destroyOpenChannelsCall(@javax.annotation.Nonnull OpenChannelDestroyRequest openChannelDestroyRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelDestroyRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/destroy";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call destroyOpenChannelsValidateBeforeCall(@javax.annotation.Nonnull OpenChannelDestroyRequest openChannelDestroyRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelDestroyRequest' is set
        if (openChannelDestroyRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelDestroyRequest' when calling destroyOpenChannels(Async)");
        }

        
        return destroyOpenChannelsCall(openChannelDestroyRequest, _callback);

    }

    /**
     * Destroy an open channel
     * Rate limit: 100/sec.
     * @param openChannelDestroyRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/destroy">Destroy an open channel Documentation</a>
     */
    public CodeOnlyResponse destroyOpenChannels(@javax.annotation.Nonnull OpenChannelDestroyRequest openChannelDestroyRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = destroyOpenChannelsWithHttpInfo(openChannelDestroyRequest);
        return localVarResp.getData();
    }

    /**
     * Destroy an open channel
     * Rate limit: 100/sec.
     * @param openChannelDestroyRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/destroy">Destroy an open channel Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> destroyOpenChannelsWithHttpInfo(@javax.annotation.Nonnull OpenChannelDestroyRequest openChannelDestroyRequest) throws ApiException {
        okhttp3.Call localVarCall = destroyOpenChannelsValidateBeforeCall(openChannelDestroyRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Destroy an open channel (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelDestroyRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/destroy">Destroy an open channel Documentation</a>
     */
    public okhttp3.Call destroyOpenChannelsAsync(@javax.annotation.Nonnull OpenChannelDestroyRequest openChannelDestroyRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = destroyOpenChannelsValidateBeforeCall(openChannelDestroyRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for getOpenChannel
     * @param openChannelGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/get">Get open channel info Documentation</a>
     */
    public okhttp3.Call getOpenChannelCall(@javax.annotation.Nonnull OpenChannelGetRequest openChannelGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelGetRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call getOpenChannelValidateBeforeCall(@javax.annotation.Nonnull OpenChannelGetRequest openChannelGetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelGetRequest' is set
        if (openChannelGetRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelGetRequest' when calling getOpenChannel(Async)");
        }

        
        return getOpenChannelCall(openChannelGetRequest, _callback);

    }

    /**
     * Get open channel info
     * Rate limit: 100/sec.
     * @param openChannelGetRequest  (required)
     * @return OpenChannelGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/get">Get open channel info Documentation</a>
     */
    public OpenChannelGetResponse getOpenChannel(@javax.annotation.Nonnull OpenChannelGetRequest openChannelGetRequest) throws ApiException {
        ApiResponse<OpenChannelGetResponse> localVarResp = getOpenChannelWithHttpInfo(openChannelGetRequest);
        return localVarResp.getData();
    }

    /**
     * Get open channel info
     * Rate limit: 100/sec.
     * @param openChannelGetRequest  (required)
     * @return ApiResponse&lt;OpenChannelGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/get">Get open channel info Documentation</a>
     */
    public ApiResponse<OpenChannelGetResponse> getOpenChannelWithHttpInfo(@javax.annotation.Nonnull OpenChannelGetRequest openChannelGetRequest) throws ApiException {
        okhttp3.Call localVarCall = getOpenChannelValidateBeforeCall(openChannelGetRequest, null);
        Type localVarReturnType = new TypeToken<OpenChannelGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Get open channel info (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/get">Get open channel info Documentation</a>
     */
    public okhttp3.Call getOpenChannelAsync(@javax.annotation.Nonnull OpenChannelGetRequest openChannelGetRequest, final ApiCallback<OpenChannelGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOpenChannelValidateBeforeCall(openChannelGetRequest, _callback);
        Type localVarReturnType = new TypeToken<OpenChannelGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
        /**
     * Build call for setOpenChannelDestroyType
     * @param openChannelDestroyTypeSetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/set-destroy-type">Set auto-destroy type Documentation</a>
     */
    public okhttp3.Call setOpenChannelDestroyTypeCall(@javax.annotation.Nonnull OpenChannelDestroyTypeSetRequest openChannelDestroyTypeSetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = openChannelDestroyTypeSetRequest;
                // create path and map variables
        String localVarPath = "/v4/open-channel/destroy-type/set";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "NexconnSignature" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

            @SuppressWarnings("rawtypes")
    private okhttp3.Call setOpenChannelDestroyTypeValidateBeforeCall(@javax.annotation.Nonnull OpenChannelDestroyTypeSetRequest openChannelDestroyTypeSetRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'openChannelDestroyTypeSetRequest' is set
        if (openChannelDestroyTypeSetRequest == null) {
            throw new ApiException("Missing the required parameter 'openChannelDestroyTypeSetRequest' when calling setOpenChannelDestroyType(Async)");
        }

        
        return setOpenChannelDestroyTypeCall(openChannelDestroyTypeSetRequest, _callback);

    }

    /**
     * Set auto-destroy type
     * Rate limit: 100/sec.
     * @param openChannelDestroyTypeSetRequest  (required)
     * @return CodeOnlyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/set-destroy-type">Set auto-destroy type Documentation</a>
     */
    public CodeOnlyResponse setOpenChannelDestroyType(@javax.annotation.Nonnull OpenChannelDestroyTypeSetRequest openChannelDestroyTypeSetRequest) throws ApiException {
        ApiResponse<CodeOnlyResponse> localVarResp = setOpenChannelDestroyTypeWithHttpInfo(openChannelDestroyTypeSetRequest);
        return localVarResp.getData();
    }

    /**
     * Set auto-destroy type
     * Rate limit: 100/sec.
     * @param openChannelDestroyTypeSetRequest  (required)
     * @return ApiResponse&lt;CodeOnlyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/set-destroy-type">Set auto-destroy type Documentation</a>
     */
    public ApiResponse<CodeOnlyResponse> setOpenChannelDestroyTypeWithHttpInfo(@javax.annotation.Nonnull OpenChannelDestroyTypeSetRequest openChannelDestroyTypeSetRequest) throws ApiException {
        okhttp3.Call localVarCall = setOpenChannelDestroyTypeValidateBeforeCall(openChannelDestroyTypeSetRequest, null);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
    

    /**
     * Set auto-destroy type (asynchronously)
     * Rate limit: 100/sec.
     * @param openChannelDestroyTypeSetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     * Official documentation
     * @see <a href="https://docs.nexconn.ai/platform-chat-api/open-channel/set-destroy-type">Set auto-destroy type Documentation</a>
     */
    public okhttp3.Call setOpenChannelDestroyTypeAsync(@javax.annotation.Nonnull OpenChannelDestroyTypeSetRequest openChannelDestroyTypeSetRequest, final ApiCallback<CodeOnlyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = setOpenChannelDestroyTypeValidateBeforeCall(openChannelDestroyTypeSetRequest, _callback);
        Type localVarReturnType = new TypeToken<CodeOnlyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    }
