/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import ai.nexconn.model.MessageMetadataListItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelTypeMessageMetadataListResponseResult
 */
public class ChannelTypeMessageMetadataListResponseResultTest {
    private final ChannelTypeMessageMetadataListResponseResult model = new ChannelTypeMessageMetadataListResponseResult();

    /**
     * Model tests for ChannelTypeMessageMetadataListResponseResult
     */
    @Test
    public void testChannelTypeMessageMetadataListResponseResult() {
        // TODO: test ChannelTypeMessageMetadataListResponseResult
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
