/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import ai.nexconn.model.ChannelTagTargetItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelTagListResponseResult
 */
public class ChannelTagListResponseResultTest {
    private final ChannelTagListResponseResult model = new ChannelTagListResponseResult();

    /**
     * Model tests for ChannelTagListResponseResult
     */
    @Test
    public void testChannelTagListResponseResult() {
        // TODO: test ChannelTagListResponseResult
    }

    /**
     * Test the property 'tagId'
     */
    @Test
    public void tagIdTest() {
        // TODO: test tagId
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

}
