/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CommunityUserSubchannelListResponseResult
 */
public class CommunityUserSubchannelListResponseResultTest {
    private final CommunityUserSubchannelListResponseResult model = new CommunityUserSubchannelListResponseResult();

    /**
     * Model tests for CommunityUserSubchannelListResponseResult
     */
    @Test
    public void testCommunityUserSubchannelListResponseResult() {
        // TODO: test CommunityUserSubchannelListResponseResult
    }

    /**
     * Test the property 'subChannels'
     */
    @Test
    public void subChannelsTest() {
        // TODO: test subChannels
    }

}
