/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GroupChannelProfileUpdateRequest
 */
public class GroupChannelProfileUpdateRequestTest {
    private final GroupChannelProfileUpdateRequest model = new GroupChannelProfileUpdateRequest();

    /**
     * Model tests for GroupChannelProfileUpdateRequest
     */
    @Test
    public void testGroupChannelProfileUpdateRequest() {
        // TODO: test GroupChannelProfileUpdateRequest
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'groupProfile'
     */
    @Test
    public void groupProfileTest() {
        // TODO: test groupProfile
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'groupExtProfile'
     */
    @Test
    public void groupExtProfileTest() {
        // TODO: test groupExtProfile
    }

}
