/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GroupChannelTransferOwnerRequest
 */
public class GroupChannelTransferOwnerRequestTest {
    private final GroupChannelTransferOwnerRequest model = new GroupChannelTransferOwnerRequest();

    /**
     * Model tests for GroupChannelTransferOwnerRequest
     */
    @Test
    public void testGroupChannelTransferOwnerRequest() {
        // TODO: test GroupChannelTransferOwnerRequest
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'newOwner'
     */
    @Test
    public void newOwnerTest() {
        // TODO: test newOwner
    }

    /**
     * Test the property 'shouldLeave'
     */
    @Test
    public void shouldLeaveTest() {
        // TODO: test shouldLeave
    }

    /**
     * Test the property 'shouldDeleteMute'
     */
    @Test
    public void shouldDeleteMuteTest() {
        // TODO: test shouldDeleteMute
    }

    /**
     * Test the property 'shouldDeleteAllowedSendersList'
     */
    @Test
    public void shouldDeleteAllowedSendersListTest() {
        // TODO: test shouldDeleteAllowedSendersList
    }

    /**
     * Test the property 'shouldDeleteFavorites'
     */
    @Test
    public void shouldDeleteFavoritesTest() {
        // TODO: test shouldDeleteFavorites
    }

}
