/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import ai.nexconn.model.MessageMetadataListItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageRecord
 */
public class MessageRecordTest {
    private final MessageRecord model = new MessageRecord();

    /**
     * Model tests for MessageRecord
     */
    @Test
    public void testMessageRecord() {
        // TODO: test MessageRecord
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'subchannelId'
     */
    @Test
    public void subchannelIdTest() {
        // TODO: test subchannelId
    }

    /**
     * Test the property 'fromUserId'
     */
    @Test
    public void fromUserIdTest() {
        // TODO: test fromUserId
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'sentAt'
     */
    @Test
    public void sentAtTest() {
        // TODO: test sentAt
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'channelType'
     */
    @Test
    public void channelTypeTest() {
        // TODO: test channelType
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'hasMetadata'
     */
    @Test
    public void hasMetadataTest() {
        // TODO: test hasMetadata
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
