/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OpenChannelFreezeListUpdateRequest
 */
public class OpenChannelFreezeListUpdateRequestTest {
    private final OpenChannelFreezeListUpdateRequest model = new OpenChannelFreezeListUpdateRequest();

    /**
     * Model tests for OpenChannelFreezeListUpdateRequest
     */
    @Test
    public void testOpenChannelFreezeListUpdateRequest() {
        // TODO: test OpenChannelFreezeListUpdateRequest
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'needNotify'
     */
    @Test
    public void needNotifyTest() {
        // TODO: test needNotify
    }

}
