/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OpenChannelCreateRequest
 */
public class OpenChannelCreateRequestTest {
    private final OpenChannelCreateRequest model = new OpenChannelCreateRequest();

    /**
     * Model tests for OpenChannelCreateRequest
     */
    @Test
    public void testOpenChannelCreateRequest() {
        // TODO: test OpenChannelCreateRequest
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'destroyType'
     */
    @Test
    public void destroyTypeTest() {
        // TODO: test destroyType
    }

    /**
     * Test the property 'ttlMinutes'
     */
    @Test
    public void ttlMinutesTest() {
        // TODO: test ttlMinutes
    }

    /**
     * Test the property 'shouldFreeze'
     */
    @Test
    public void shouldFreezeTest() {
        // TODO: test shouldFreeze
    }

    /**
     * Test the property 'allowedSendersList'
     */
    @Test
    public void allowedSendersListTest() {
        // TODO: test allowedSendersList
    }

    /**
     * Test the property 'metadataOwnerId'
     */
    @Test
    public void metadataOwnerIdTest() {
        // TODO: test metadataOwnerId
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
