/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SystemChannelMessageSendRequest
 */
public class SystemChannelMessageSendRequestTest {
    private final SystemChannelMessageSendRequest model = new SystemChannelMessageSendRequest();

    /**
     * Model tests for SystemChannelMessageSendRequest
     */
    @Test
    public void testSystemChannelMessageSendRequest() {
        // TODO: test SystemChannelMessageSendRequest
    }

    /**
     * Test the property 'fromUserId'
     */
    @Test
    public void fromUserIdTest() {
        // TODO: test fromUserId
    }

    /**
     * Test the property 'toUserIds'
     */
    @Test
    public void toUserIdsTest() {
        // TODO: test toUserIds
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'pushContent'
     */
    @Test
    public void pushContentTest() {
        // TODO: test pushContent
    }

    /**
     * Test the property 'pushData'
     */
    @Test
    public void pushDataTest() {
        // TODO: test pushData
    }

    /**
     * Test the property 'shouldPersist'
     */
    @Test
    public void shouldPersistTest() {
        // TODO: test shouldPersist
    }

    /**
     * Test the property 'contentAvailable'
     */
    @Test
    public void contentAvailableTest() {
        // TODO: test contentAvailable
    }

    /**
     * Test the property 'disablePush'
     */
    @Test
    public void disablePushTest() {
        // TODO: test disablePush
    }

    /**
     * Test the property 'pushExt'
     */
    @Test
    public void pushExtTest() {
        // TODO: test pushExt
    }

    /**
     * Test the property 'disableUpdateLastMsg'
     */
    @Test
    public void disableUpdateLastMsgTest() {
        // TODO: test disableUpdateLastMsg
    }

}
