/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * ChannelTypeNotificationGetRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ChannelTypeNotificationGetRequest {
  public static final String SERIALIZED_NAME_CHANNEL_TYPE = "channelType";
  @SerializedName(SERIALIZED_NAME_CHANNEL_TYPE)
  @javax.annotation.Nonnull
  private String channelType;

  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @javax.annotation.Nonnull
  private String requestId;

  public ChannelTypeNotificationGetRequest() {
  }

  public ChannelTypeNotificationGetRequest channelType(@javax.annotation.Nonnull String channelType) {
    this.channelType = channelType;
    return this;
  }

  /**
   * Session / channel type as a string (&#x60;1&#x60; to &#x60;10&#x60; as accepted by the server).
   * @return channelType
   */
  @javax.annotation.Nonnull
  public String getChannelType() {
    return channelType;
  }

  public void setChannelType(@javax.annotation.Nonnull String channelType) {
    this.channelType = channelType;
  }


  public ChannelTypeNotificationGetRequest requestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * User ID whose channel-type notification setting is queried.
   * @return requestId
   */
  @javax.annotation.Nonnull
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelTypeNotificationGetRequest channelTypeNotificationGetRequest = (ChannelTypeNotificationGetRequest) o;
    return Objects.equals(this.channelType, channelTypeNotificationGetRequest.channelType) &&
        Objects.equals(this.requestId, channelTypeNotificationGetRequest.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelType, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelTypeNotificationGetRequest {\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelType", "requestId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelType", "requestId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChannelTypeNotificationGetRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChannelTypeNotificationGetRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChannelTypeNotificationGetRequest is not found in the empty JSON string", ChannelTypeNotificationGetRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChannelTypeNotificationGetRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChannelTypeNotificationGetRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChannelTypeNotificationGetRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelType").toString()));
      }
      if (!jsonObj.get("requestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChannelTypeNotificationGetRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChannelTypeNotificationGetRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChannelTypeNotificationGetRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChannelTypeNotificationGetRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ChannelTypeNotificationGetRequest>() {
           @Override
           public void write(JsonWriter out, ChannelTypeNotificationGetRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChannelTypeNotificationGetRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChannelTypeNotificationGetRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChannelTypeNotificationGetRequest
   * @throws IOException if the JSON string is invalid with respect to ChannelTypeNotificationGetRequest
   */
  public static ChannelTypeNotificationGetRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChannelTypeNotificationGetRequest.class);
  }

  /**
   * Convert an instance of ChannelTypeNotificationGetRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

