/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * ChannelPushSetRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ChannelPushSetRequest {
  public static final String SERIALIZED_NAME_CHANNEL_TYPE = "channelType";
  @SerializedName(SERIALIZED_NAME_CHANNEL_TYPE)
  @javax.annotation.Nonnull
  private String channelType;

  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @javax.annotation.Nonnull
  private String requestId;

  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  @javax.annotation.Nonnull
  private String channelId;

  public static final String SERIALIZED_NAME_SUBCHANNEL_ID = "subchannelId";
  @SerializedName(SERIALIZED_NAME_SUBCHANNEL_ID)
  @javax.annotation.Nullable
  private String subchannelId;

  public static final String SERIALIZED_NAME_NO_DISTURB_LEVEL = "noDisturbLevel";
  @SerializedName(SERIALIZED_NAME_NO_DISTURB_LEVEL)
  @javax.annotation.Nonnull
  private Integer noDisturbLevel;

  public ChannelPushSetRequest() {
  }

  public ChannelPushSetRequest channelType(@javax.annotation.Nonnull String channelType) {
    this.channelType = channelType;
    return this;
  }

  /**
   * Session / channel type as a string (&#x60;1&#x60; to &#x60;10&#x60; as accepted by the server). Matches &#x60;ChannelTypeRequestInput&#x60; in the service.
   * @return channelType
   */
  @javax.annotation.Nonnull
  public String getChannelType() {
    return channelType;
  }

  public void setChannelType(@javax.annotation.Nonnull String channelType) {
    this.channelType = channelType;
  }


  public ChannelPushSetRequest requestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * User ID whose channel notification setting is updated.
   * @return requestId
   */
  @javax.annotation.Nonnull
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
  }


  public ChannelPushSetRequest channelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Legacy &#x60;targetId&#x60;.
   * @return channelId
   */
  @javax.annotation.Nonnull
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
  }


  public ChannelPushSetRequest subchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
    return this;
  }

  /**
   * Legacy &#x60;busChannel&#x60;. Used for community-channel subchannel level settings.
   * @return subchannelId
   */
  @javax.annotation.Nullable
  public String getSubchannelId() {
    return subchannelId;
  }

  public void setSubchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
  }


  public ChannelPushSetRequest noDisturbLevel(@javax.annotation.Nonnull Integer noDisturbLevel) {
    this.noDisturbLevel = noDisturbLevel;
    return this;
  }

  /**
   * Do-not-disturb level (required by service validation; range &#x60;-1&#x60; to &#x60;5&#x60;).
   * @return noDisturbLevel
   */
  @javax.annotation.Nonnull
  public Integer getNoDisturbLevel() {
    return noDisturbLevel;
  }

  public void setNoDisturbLevel(@javax.annotation.Nonnull Integer noDisturbLevel) {
    this.noDisturbLevel = noDisturbLevel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelPushSetRequest channelPushSetRequest = (ChannelPushSetRequest) o;
    return Objects.equals(this.channelType, channelPushSetRequest.channelType) &&
        Objects.equals(this.requestId, channelPushSetRequest.requestId) &&
        Objects.equals(this.channelId, channelPushSetRequest.channelId) &&
        Objects.equals(this.subchannelId, channelPushSetRequest.subchannelId) &&
        Objects.equals(this.noDisturbLevel, channelPushSetRequest.noDisturbLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelType, requestId, channelId, subchannelId, noDisturbLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelPushSetRequest {\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    subchannelId: ").append(toIndentedString(subchannelId)).append("\n");
    sb.append("    noDisturbLevel: ").append(toIndentedString(noDisturbLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelType", "requestId", "channelId", "subchannelId", "noDisturbLevel"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelType", "requestId", "channelId", "noDisturbLevel"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChannelPushSetRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChannelPushSetRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChannelPushSetRequest is not found in the empty JSON string", ChannelPushSetRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChannelPushSetRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChannelPushSetRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChannelPushSetRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelType").toString()));
      }
      if (!jsonObj.get("requestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestId").toString()));
      }
      if (!jsonObj.get("channelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelId").toString()));
      }
      if ((jsonObj.get("subchannelId") != null && !jsonObj.get("subchannelId").isJsonNull()) && !jsonObj.get("subchannelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subchannelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subchannelId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChannelPushSetRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChannelPushSetRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChannelPushSetRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChannelPushSetRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ChannelPushSetRequest>() {
           @Override
           public void write(JsonWriter out, ChannelPushSetRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChannelPushSetRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChannelPushSetRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChannelPushSetRequest
   * @throws IOException if the JSON string is invalid with respect to ChannelPushSetRequest
   */
  public static ChannelPushSetRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChannelPushSetRequest.class);
  }

  /**
   * Convert an instance of ChannelPushSetRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

