/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import ai.nexconn.model.MessageChannelDelivery;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * ChannelMessageSendResponseResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ChannelMessageSendResponseResult {
  public static final String SERIALIZED_NAME_MESSAGE_IDS = "messageIds";
  @SerializedName(SERIALIZED_NAME_MESSAGE_IDS)
  @javax.annotation.Nullable
  private List<MessageChannelDelivery> messageIds = new ArrayList<>();

  public ChannelMessageSendResponseResult() {
  }

  public ChannelMessageSendResponseResult messageIds(@javax.annotation.Nullable List<MessageChannelDelivery> messageIds) {
    this.messageIds = messageIds;
    return this;
  }

  public ChannelMessageSendResponseResult addMessageIdsItem(MessageChannelDelivery messageIdsItem) {
    if (this.messageIds == null) {
      this.messageIds = new ArrayList<>();
    }
    this.messageIds.add(messageIdsItem);
    return this;
  }

  /**
   * Get messageIds
   * @return messageIds
   */
  @javax.annotation.Nullable
  public List<MessageChannelDelivery> getMessageIds() {
    return messageIds;
  }

  public void setMessageIds(@javax.annotation.Nullable List<MessageChannelDelivery> messageIds) {
    this.messageIds = messageIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelMessageSendResponseResult channelMessageSendResponseResult = (ChannelMessageSendResponseResult) o;
    return Objects.equals(this.messageIds, channelMessageSendResponseResult.messageIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelMessageSendResponseResult {\n");
    sb.append("    messageIds: ").append(toIndentedString(messageIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("messageIds"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChannelMessageSendResponseResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChannelMessageSendResponseResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChannelMessageSendResponseResult is not found in the empty JSON string", ChannelMessageSendResponseResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChannelMessageSendResponseResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChannelMessageSendResponseResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("messageIds") != null && !jsonObj.get("messageIds").isJsonNull()) {
        JsonArray jsonArraymessageIds = jsonObj.getAsJsonArray("messageIds");
        if (jsonArraymessageIds != null) {
          // ensure the json data is an array
          if (!jsonObj.get("messageIds").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `messageIds` to be an array in the JSON string but got `%s`", jsonObj.get("messageIds").toString()));
          }

          // validate the optional field `messageIds` (array)
          for (int i = 0; i < jsonArraymessageIds.size(); i++) {
            MessageChannelDelivery.validateJsonElement(jsonArraymessageIds.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChannelMessageSendResponseResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChannelMessageSendResponseResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChannelMessageSendResponseResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChannelMessageSendResponseResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ChannelMessageSendResponseResult>() {
           @Override
           public void write(JsonWriter out, ChannelMessageSendResponseResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChannelMessageSendResponseResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChannelMessageSendResponseResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChannelMessageSendResponseResult
   * @throws IOException if the JSON string is invalid with respect to ChannelMessageSendResponseResult
   */
  public static ChannelMessageSendResponseResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChannelMessageSendResponseResult.class);
  }

  /**
   * Convert an instance of ChannelMessageSendResponseResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

