/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * CommunitySubchannelKeyRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CommunitySubchannelKeyRequest {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  @javax.annotation.Nonnull
  private String channelId;

  public static final String SERIALIZED_NAME_SUBCHANNEL_ID = "subchannelId";
  @SerializedName(SERIALIZED_NAME_SUBCHANNEL_ID)
  @javax.annotation.Nonnull
  private String subchannelId;

  public CommunitySubchannelKeyRequest() {
  }

  public CommunitySubchannelKeyRequest channelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Get channelId
   * @return channelId
   */
  @javax.annotation.Nonnull
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
  }


  public CommunitySubchannelKeyRequest subchannelId(@javax.annotation.Nonnull String subchannelId) {
    this.subchannelId = subchannelId;
    return this;
  }

  /**
   * Get subchannelId
   * @return subchannelId
   */
  @javax.annotation.Nonnull
  public String getSubchannelId() {
    return subchannelId;
  }

  public void setSubchannelId(@javax.annotation.Nonnull String subchannelId) {
    this.subchannelId = subchannelId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunitySubchannelKeyRequest communitySubchannelKeyRequest = (CommunitySubchannelKeyRequest) o;
    return Objects.equals(this.channelId, communitySubchannelKeyRequest.channelId) &&
        Objects.equals(this.subchannelId, communitySubchannelKeyRequest.subchannelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, subchannelId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunitySubchannelKeyRequest {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    subchannelId: ").append(toIndentedString(subchannelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelId", "subchannelId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelId", "subchannelId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommunitySubchannelKeyRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommunitySubchannelKeyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommunitySubchannelKeyRequest is not found in the empty JSON string", CommunitySubchannelKeyRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommunitySubchannelKeyRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommunitySubchannelKeyRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CommunitySubchannelKeyRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelId").toString()));
      }
      if (!jsonObj.get("subchannelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subchannelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subchannelId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommunitySubchannelKeyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommunitySubchannelKeyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommunitySubchannelKeyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommunitySubchannelKeyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CommunitySubchannelKeyRequest>() {
           @Override
           public void write(JsonWriter out, CommunitySubchannelKeyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommunitySubchannelKeyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommunitySubchannelKeyRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommunitySubchannelKeyRequest
   * @throws IOException if the JSON string is invalid with respect to CommunitySubchannelKeyRequest
   */
  public static CommunitySubchannelKeyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommunitySubchannelKeyRequest.class);
  }

  /**
   * Convert an instance of CommunitySubchannelKeyRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

