/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * CommunityChannelFreezeListGetRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CommunityChannelFreezeListGetRequest {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  @javax.annotation.Nonnull
  private String channelId;

  public static final String SERIALIZED_NAME_SUBCHANNEL_ID = "subchannelId";
  @SerializedName(SERIALIZED_NAME_SUBCHANNEL_ID)
  @javax.annotation.Nullable
  private String subchannelId;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  @javax.annotation.Nullable
  private Integer page = 1;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Integer pageSize = 50;

  public CommunityChannelFreezeListGetRequest() {
  }

  public CommunityChannelFreezeListGetRequest channelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Get channelId
   * @return channelId
   */
  @javax.annotation.Nonnull
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
  }


  public CommunityChannelFreezeListGetRequest subchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
    return this;
  }

  /**
   * Get subchannelId
   * @return subchannelId
   */
  @javax.annotation.Nullable
  public String getSubchannelId() {
    return subchannelId;
  }

  public void setSubchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
  }


  public CommunityChannelFreezeListGetRequest page(@javax.annotation.Nullable Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Pagination field from &#x60;CommunityAllowedSenderListInput&#x60; / &#x60;AbstractCommunityPagingInput&#x60; (present in Java model; not all server code paths consume it).
   * @return page
   */
  @javax.annotation.Nullable
  public Integer getPage() {
    return page;
  }

  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }


  public CommunityChannelFreezeListGetRequest pageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest = (CommunityChannelFreezeListGetRequest) o;
    return Objects.equals(this.channelId, communityChannelFreezeListGetRequest.channelId) &&
        Objects.equals(this.subchannelId, communityChannelFreezeListGetRequest.subchannelId) &&
        Objects.equals(this.page, communityChannelFreezeListGetRequest.page) &&
        Objects.equals(this.pageSize, communityChannelFreezeListGetRequest.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, subchannelId, page, pageSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunityChannelFreezeListGetRequest {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    subchannelId: ").append(toIndentedString(subchannelId)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelId", "subchannelId", "page", "pageSize"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommunityChannelFreezeListGetRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommunityChannelFreezeListGetRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommunityChannelFreezeListGetRequest is not found in the empty JSON string", CommunityChannelFreezeListGetRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommunityChannelFreezeListGetRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommunityChannelFreezeListGetRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CommunityChannelFreezeListGetRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelId").toString()));
      }
      if ((jsonObj.get("subchannelId") != null && !jsonObj.get("subchannelId").isJsonNull()) && !jsonObj.get("subchannelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subchannelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subchannelId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommunityChannelFreezeListGetRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommunityChannelFreezeListGetRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommunityChannelFreezeListGetRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommunityChannelFreezeListGetRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CommunityChannelFreezeListGetRequest>() {
           @Override
           public void write(JsonWriter out, CommunityChannelFreezeListGetRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommunityChannelFreezeListGetRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommunityChannelFreezeListGetRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommunityChannelFreezeListGetRequest
   * @throws IOException if the JSON string is invalid with respect to CommunityChannelFreezeListGetRequest
   */
  public static CommunityChannelFreezeListGetRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommunityChannelFreezeListGetRequest.class);
  }

  /**
   * Convert an instance of CommunityChannelFreezeListGetRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

