/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * CommunityChannelMessageSendRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CommunityChannelMessageSendRequest {
  public static final String SERIALIZED_NAME_FROM_USER_ID = "fromUserId";
  @SerializedName(SERIALIZED_NAME_FROM_USER_ID)
  @javax.annotation.Nonnull
  private String fromUserId;

  public static final String SERIALIZED_NAME_TO_CHANNEL_IDS = "toChannelIds";
  @SerializedName(SERIALIZED_NAME_TO_CHANNEL_IDS)
  @javax.annotation.Nonnull
  private List<String> toChannelIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_TO_USER_IDS = "toUserIds";
  @SerializedName(SERIALIZED_NAME_TO_USER_IDS)
  @javax.annotation.Nullable
  private List<String> toUserIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_MESSAGE_TYPE = "messageType";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TYPE)
  @javax.annotation.Nonnull
  private String messageType;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nonnull
  private String content;

  public static final String SERIALIZED_NAME_PUSH_CONTENT = "pushContent";
  @SerializedName(SERIALIZED_NAME_PUSH_CONTENT)
  @javax.annotation.Nullable
  private String pushContent;

  public static final String SERIALIZED_NAME_PUSH_DATA = "pushData";
  @SerializedName(SERIALIZED_NAME_PUSH_DATA)
  @javax.annotation.Nullable
  private String pushData;

  public static final String SERIALIZED_NAME_SHOULD_PERSIST = "shouldPersist";
  @SerializedName(SERIALIZED_NAME_SHOULD_PERSIST)
  @javax.annotation.Nullable
  private Integer shouldPersist;

  public static final String SERIALIZED_NAME_IS_COUNTED = "isCounted";
  @SerializedName(SERIALIZED_NAME_IS_COUNTED)
  @javax.annotation.Nullable
  private Integer isCounted;

  public static final String SERIALIZED_NAME_HAS_MENTION = "hasMention";
  @SerializedName(SERIALIZED_NAME_HAS_MENTION)
  @javax.annotation.Nullable
  private Integer hasMention;

  public static final String SERIALIZED_NAME_CONTENT_AVAILABLE = "contentAvailable";
  @SerializedName(SERIALIZED_NAME_CONTENT_AVAILABLE)
  @javax.annotation.Nullable
  private Integer contentAvailable;

  public static final String SERIALIZED_NAME_PUSH_EXT = "pushExt";
  @SerializedName(SERIALIZED_NAME_PUSH_EXT)
  @javax.annotation.Nullable
  private String pushExt;

  public static final String SERIALIZED_NAME_SUBCHANNEL_ID = "subchannelId";
  @SerializedName(SERIALIZED_NAME_SUBCHANNEL_ID)
  @javax.annotation.Nullable
  private String subchannelId;

  public static final String SERIALIZED_NAME_HAS_METADATA = "hasMetadata";
  @SerializedName(SERIALIZED_NAME_HAS_METADATA)
  @javax.annotation.Nullable
  private Boolean hasMetadata;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public CommunityChannelMessageSendRequest() {
  }

  public CommunityChannelMessageSendRequest fromUserId(@javax.annotation.Nonnull String fromUserId) {
    this.fromUserId = fromUserId;
    return this;
  }

  /**
   * Sender user ID. Non-members can send through the server API, but push display works best when the sender has an access token.
   * @return fromUserId
   */
  @javax.annotation.Nonnull
  public String getFromUserId() {
    return fromUserId;
  }

  public void setFromUserId(@javax.annotation.Nonnull String fromUserId) {
    this.fromUserId = fromUserId;
  }


  public CommunityChannelMessageSendRequest toChannelIds(@javax.annotation.Nonnull List<String> toChannelIds) {
    this.toChannelIds = toChannelIds;
    return this;
  }

  public CommunityChannelMessageSendRequest addToChannelIdsItem(String toChannelIdsItem) {
    if (this.toChannelIds == null) {
      this.toChannelIds = new ArrayList<>();
    }
    this.toChannelIds.add(toChannelIdsItem);
    return this;
  }

  /**
   * Target community channel IDs. Up to 3 community channels are supported per request.
   * @return toChannelIds
   */
  @javax.annotation.Nonnull
  public List<String> getToChannelIds() {
    return toChannelIds;
  }

  public void setToChannelIds(@javax.annotation.Nonnull List<String> toChannelIds) {
    this.toChannelIds = toChannelIds;
  }


  public CommunityChannelMessageSendRequest toUserIds(@javax.annotation.Nullable List<String> toUserIds) {
    this.toUserIds = toUserIds;
    return this;
  }

  public CommunityChannelMessageSendRequest addToUserIdsItem(String toUserIdsItem) {
    if (this.toUserIds == null) {
      this.toUserIds = new ArrayList<>();
    }
    this.toUserIds.add(toUserIdsItem);
    return this;
  }

  /**
   * Recipient member user IDs for a targeted community message. Only effective when sending to a single community channel.
   * @return toUserIds
   */
  @javax.annotation.Nullable
  public List<String> getToUserIds() {
    return toUserIds;
  }

  public void setToUserIds(@javax.annotation.Nullable List<String> toUserIds) {
    this.toUserIds = toUserIds;
  }


  public CommunityChannelMessageSendRequest messageType(@javax.annotation.Nonnull String messageType) {
    this.messageType = messageType;
    return this;
  }

  /**
   * Message type. Supports built-in types and custom types registered in the client SDK. Custom types must not start with &#x60;RC:&#x60; and must not exceed 32 characters.
   * @return messageType
   */
  @javax.annotation.Nonnull
  public String getMessageType() {
    return messageType;
  }

  public void setMessageType(@javax.annotation.Nonnull String messageType) {
    this.messageType = messageType;
  }


  public CommunityChannelMessageSendRequest content(@javax.annotation.Nonnull String content) {
    this.content = content;
    return this;
  }

  /**
   * Message content payload serialized as a string. Built-in message types should use a JSON object string. Maximum size is 128 KB.
   * @return content
   */
  @javax.annotation.Nonnull
  public String getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nonnull String content) {
    this.content = content;
  }


  public CommunityChannelMessageSendRequest pushContent(@javax.annotation.Nullable String pushContent) {
    this.pushContent = pushContent;
    return this;
  }

  /**
   * Push notification text for offline recipients. Optional for built-in user content messages and required for push-enabled custom or notification messages.
   * @return pushContent
   */
  @javax.annotation.Nullable
  public String getPushContent() {
    return pushContent;
  }

  public void setPushContent(@javax.annotation.Nullable String pushContent) {
    this.pushContent = pushContent;
  }


  public CommunityChannelMessageSendRequest pushData(@javax.annotation.Nullable String pushData) {
    this.pushData = pushData;
    return this;
  }

  /**
   * Custom push payload data. Exposed as &#x60;appData&#x60; on mobile push payloads.
   * @return pushData
   */
  @javax.annotation.Nullable
  public String getPushData() {
    return pushData;
  }

  public void setPushData(@javax.annotation.Nullable String pushData) {
    this.pushData = pushData;
  }


  public CommunityChannelMessageSendRequest shouldPersist(@javax.annotation.Nullable Integer shouldPersist) {
    this.shouldPersist = shouldPersist;
    return this;
  }

  /**
   * Whether to store the message in community message history. &#x60;0&#x60; means do not store and &#x60;1&#x60; means store.
   * @return shouldPersist
   */
  @javax.annotation.Nullable
  public Integer getShouldPersist() {
    return shouldPersist;
  }

  public void setShouldPersist(@javax.annotation.Nullable Integer shouldPersist) {
    this.shouldPersist = shouldPersist;
  }


  public CommunityChannelMessageSendRequest isCounted(@javax.annotation.Nullable Integer isCounted) {
    this.isCounted = isCounted;
    return this;
  }

  /**
   * Whether to count this message as unread for offline users. &#x60;1&#x60; counts as unread and &#x60;0&#x60; does not.
   * @return isCounted
   */
  @javax.annotation.Nullable
  public Integer getIsCounted() {
    return isCounted;
  }

  public void setIsCounted(@javax.annotation.Nullable Integer isCounted) {
    this.isCounted = isCounted;
  }


  public CommunityChannelMessageSendRequest hasMention(@javax.annotation.Nullable Integer hasMention) {
    this.hasMention = hasMention;
    return this;
  }

  /**
   * Whether this is an @mention message. Set to &#x60;1&#x60; when &#x60;content&#x60; contains &#x60;mentionedInfo&#x60;.
   * @return hasMention
   */
  @javax.annotation.Nullable
  public Integer getHasMention() {
    return hasMention;
  }

  public void setHasMention(@javax.annotation.Nullable Integer hasMention) {
    this.hasMention = hasMention;
  }


  public CommunityChannelMessageSendRequest contentAvailable(@javax.annotation.Nullable Integer contentAvailable) {
    this.contentAvailable = contentAvailable;
    return this;
  }

  /**
   * iOS silent-push flag. &#x60;1&#x60; enables background delivery and &#x60;0&#x60; disables it.
   * @return contentAvailable
   */
  @javax.annotation.Nullable
  public Integer getContentAvailable() {
    return contentAvailable;
  }

  public void setContentAvailable(@javax.annotation.Nullable Integer contentAvailable) {
    this.contentAvailable = contentAvailable;
  }


  public CommunityChannelMessageSendRequest pushExt(@javax.annotation.Nullable String pushExt) {
    this.pushExt = pushExt;
    return this;
  }

  /**
   * Extended push configuration (JSON string as accepted by the server &#x60;CommunityChannelMsgSendInput&#x60;).
   * @return pushExt
   */
  @javax.annotation.Nullable
  public String getPushExt() {
    return pushExt;
  }

  public void setPushExt(@javax.annotation.Nullable String pushExt) {
    this.pushExt = pushExt;
  }


  public CommunityChannelMessageSendRequest subchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
    return this;
  }

  /**
   * Target subchannel ID. If omitted, delivery follows the app&#39;s default community-channel behavior.
   * @return subchannelId
   */
  @javax.annotation.Nullable
  public String getSubchannelId() {
    return subchannelId;
  }

  public void setSubchannelId(@javax.annotation.Nullable String subchannelId) {
    this.subchannelId = subchannelId;
  }


  public CommunityChannelMessageSendRequest hasMetadata(@javax.annotation.Nullable Boolean hasMetadata) {
    this.hasMetadata = hasMetadata;
    return this;
  }

  /**
   * Whether to enable message metadata for this message.
   * @return hasMetadata
   */
  @javax.annotation.Nullable
  public Boolean getHasMetadata() {
    return hasMetadata;
  }

  public void setHasMetadata(@javax.annotation.Nullable Boolean hasMetadata) {
    this.hasMetadata = hasMetadata;
  }


  public CommunityChannelMessageSendRequest metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CommunityChannelMessageSendRequest putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Custom message metadata entries. Only effective when &#x60;hasMetadata&#x60; is &#x60;true&#x60;.
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, Object> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunityChannelMessageSendRequest communityChannelMessageSendRequest = (CommunityChannelMessageSendRequest) o;
    return Objects.equals(this.fromUserId, communityChannelMessageSendRequest.fromUserId) &&
        Objects.equals(this.toChannelIds, communityChannelMessageSendRequest.toChannelIds) &&
        Objects.equals(this.toUserIds, communityChannelMessageSendRequest.toUserIds) &&
        Objects.equals(this.messageType, communityChannelMessageSendRequest.messageType) &&
        Objects.equals(this.content, communityChannelMessageSendRequest.content) &&
        Objects.equals(this.pushContent, communityChannelMessageSendRequest.pushContent) &&
        Objects.equals(this.pushData, communityChannelMessageSendRequest.pushData) &&
        Objects.equals(this.shouldPersist, communityChannelMessageSendRequest.shouldPersist) &&
        Objects.equals(this.isCounted, communityChannelMessageSendRequest.isCounted) &&
        Objects.equals(this.hasMention, communityChannelMessageSendRequest.hasMention) &&
        Objects.equals(this.contentAvailable, communityChannelMessageSendRequest.contentAvailable) &&
        Objects.equals(this.pushExt, communityChannelMessageSendRequest.pushExt) &&
        Objects.equals(this.subchannelId, communityChannelMessageSendRequest.subchannelId) &&
        Objects.equals(this.hasMetadata, communityChannelMessageSendRequest.hasMetadata) &&
        Objects.equals(this.metadata, communityChannelMessageSendRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromUserId, toChannelIds, toUserIds, messageType, content, pushContent, pushData, shouldPersist, isCounted, hasMention, contentAvailable, pushExt, subchannelId, hasMetadata, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunityChannelMessageSendRequest {\n");
    sb.append("    fromUserId: ").append(toIndentedString(fromUserId)).append("\n");
    sb.append("    toChannelIds: ").append(toIndentedString(toChannelIds)).append("\n");
    sb.append("    toUserIds: ").append(toIndentedString(toUserIds)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    pushContent: ").append(toIndentedString(pushContent)).append("\n");
    sb.append("    pushData: ").append(toIndentedString(pushData)).append("\n");
    sb.append("    shouldPersist: ").append(toIndentedString(shouldPersist)).append("\n");
    sb.append("    isCounted: ").append(toIndentedString(isCounted)).append("\n");
    sb.append("    hasMention: ").append(toIndentedString(hasMention)).append("\n");
    sb.append("    contentAvailable: ").append(toIndentedString(contentAvailable)).append("\n");
    sb.append("    pushExt: ").append(toIndentedString(pushExt)).append("\n");
    sb.append("    subchannelId: ").append(toIndentedString(subchannelId)).append("\n");
    sb.append("    hasMetadata: ").append(toIndentedString(hasMetadata)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fromUserId", "toChannelIds", "toUserIds", "messageType", "content", "pushContent", "pushData", "shouldPersist", "isCounted", "hasMention", "contentAvailable", "pushExt", "subchannelId", "hasMetadata", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("fromUserId", "toChannelIds", "messageType", "content"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommunityChannelMessageSendRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommunityChannelMessageSendRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommunityChannelMessageSendRequest is not found in the empty JSON string", CommunityChannelMessageSendRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommunityChannelMessageSendRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommunityChannelMessageSendRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CommunityChannelMessageSendRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fromUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fromUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromUserId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("toChannelIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("toChannelIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `toChannelIds` to be an array in the JSON string but got `%s`", jsonObj.get("toChannelIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("toUserIds") != null && !jsonObj.get("toUserIds").isJsonNull() && !jsonObj.get("toUserIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `toUserIds` to be an array in the JSON string but got `%s`", jsonObj.get("toUserIds").toString()));
      }
      if (!jsonObj.get("messageType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `messageType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("messageType").toString()));
      }
      if (!jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if ((jsonObj.get("pushContent") != null && !jsonObj.get("pushContent").isJsonNull()) && !jsonObj.get("pushContent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pushContent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pushContent").toString()));
      }
      if ((jsonObj.get("pushData") != null && !jsonObj.get("pushData").isJsonNull()) && !jsonObj.get("pushData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pushData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pushData").toString()));
      }
      if ((jsonObj.get("pushExt") != null && !jsonObj.get("pushExt").isJsonNull()) && !jsonObj.get("pushExt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pushExt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pushExt").toString()));
      }
      if ((jsonObj.get("subchannelId") != null && !jsonObj.get("subchannelId").isJsonNull()) && !jsonObj.get("subchannelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subchannelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subchannelId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommunityChannelMessageSendRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommunityChannelMessageSendRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommunityChannelMessageSendRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommunityChannelMessageSendRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CommunityChannelMessageSendRequest>() {
           @Override
           public void write(JsonWriter out, CommunityChannelMessageSendRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommunityChannelMessageSendRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommunityChannelMessageSendRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommunityChannelMessageSendRequest
   * @throws IOException if the JSON string is invalid with respect to CommunityChannelMessageSendRequest
   */
  public static CommunityChannelMessageSendRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommunityChannelMessageSendRequest.class);
  }

  /**
   * Convert an instance of CommunityChannelMessageSendRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

