/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * GroupChannelCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class GroupChannelCreateRequest {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  @javax.annotation.Nonnull
  private String channelId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nonnull
  private String owner;

  public static final String SERIALIZED_NAME_USER_IDS = "userIds";
  @SerializedName(SERIALIZED_NAME_USER_IDS)
  @javax.annotation.Nullable
  private List<String> userIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_GROUP_PROFILE = "groupProfile";
  @SerializedName(SERIALIZED_NAME_GROUP_PROFILE)
  @javax.annotation.Nullable
  private Map<String, Object> groupProfile = new HashMap<>();

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  @javax.annotation.Nullable
  private Map<String, Object> permissions = new HashMap<>();

  public static final String SERIALIZED_NAME_GROUP_EXT_PROFILE = "groupExtProfile";
  @SerializedName(SERIALIZED_NAME_GROUP_EXT_PROFILE)
  @javax.annotation.Nullable
  private Map<String, Object> groupExtProfile = new HashMap<>();

  public GroupChannelCreateRequest() {
  }

  public GroupChannelCreateRequest channelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Legacy &#x60;groupId&#x60;.
   * @return channelId
   */
  @javax.annotation.Nonnull
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
  }


  public GroupChannelCreateRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public GroupChannelCreateRequest owner(@javax.annotation.Nonnull String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Group owner user ID.
   * @return owner
   */
  @javax.annotation.Nonnull
  public String getOwner() {
    return owner;
  }

  public void setOwner(@javax.annotation.Nonnull String owner) {
    this.owner = owner;
  }


  public GroupChannelCreateRequest userIds(@javax.annotation.Nullable List<String> userIds) {
    this.userIds = userIds;
    return this;
  }

  public GroupChannelCreateRequest addUserIdsItem(String userIdsItem) {
    if (this.userIds == null) {
      this.userIds = new ArrayList<>();
    }
    this.userIds.add(userIdsItem);
    return this;
  }

  /**
   * Invited user IDs. The PDF limits this array to 30 users per request.
   * @return userIds
   */
  @javax.annotation.Nullable
  public List<String> getUserIds() {
    return userIds;
  }

  public void setUserIds(@javax.annotation.Nullable List<String> userIds) {
    this.userIds = userIds;
  }


  public GroupChannelCreateRequest groupProfile(@javax.annotation.Nullable Map<String, Object> groupProfile) {
    this.groupProfile = groupProfile;
    return this;
  }

  public GroupChannelCreateRequest putGroupProfileItem(String key, Object groupProfileItem) {
    if (this.groupProfile == null) {
      this.groupProfile = new HashMap<>();
    }
    this.groupProfile.put(key, groupProfileItem);
    return this;
  }

  /**
   * Group basic profile object. Common keys include &#x60;introduction&#x60;, &#x60;announcement&#x60;, and &#x60;portraitUrl&#x60;.
   * @return groupProfile
   */
  @javax.annotation.Nullable
  public Map<String, Object> getGroupProfile() {
    return groupProfile;
  }

  public void setGroupProfile(@javax.annotation.Nullable Map<String, Object> groupProfile) {
    this.groupProfile = groupProfile;
  }


  public GroupChannelCreateRequest permissions(@javax.annotation.Nullable Map<String, Object> permissions) {
    this.permissions = permissions;
    return this;
  }

  public GroupChannelCreateRequest putPermissionsItem(String key, Object permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new HashMap<>();
    }
    this.permissions.put(key, permissionsItem);
    return this;
  }

  /**
   * Group permission object defined by the source API.
   * @return permissions
   */
  @javax.annotation.Nullable
  public Map<String, Object> getPermissions() {
    return permissions;
  }

  public void setPermissions(@javax.annotation.Nullable Map<String, Object> permissions) {
    this.permissions = permissions;
  }


  public GroupChannelCreateRequest groupExtProfile(@javax.annotation.Nullable Map<String, Object> groupExtProfile) {
    this.groupExtProfile = groupExtProfile;
    return this;
  }

  public GroupChannelCreateRequest putGroupExtProfileItem(String key, Object groupExtProfileItem) {
    if (this.groupExtProfile == null) {
      this.groupExtProfile = new HashMap<>();
    }
    this.groupExtProfile.put(key, groupExtProfileItem);
    return this;
  }

  /**
   * Group extra profile object. Keys must start with &#x60;ext_&#x60; according to the PDF.
   * @return groupExtProfile
   */
  @javax.annotation.Nullable
  public Map<String, Object> getGroupExtProfile() {
    return groupExtProfile;
  }

  public void setGroupExtProfile(@javax.annotation.Nullable Map<String, Object> groupExtProfile) {
    this.groupExtProfile = groupExtProfile;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupChannelCreateRequest groupChannelCreateRequest = (GroupChannelCreateRequest) o;
    return Objects.equals(this.channelId, groupChannelCreateRequest.channelId) &&
        Objects.equals(this.name, groupChannelCreateRequest.name) &&
        Objects.equals(this.owner, groupChannelCreateRequest.owner) &&
        Objects.equals(this.userIds, groupChannelCreateRequest.userIds) &&
        Objects.equals(this.groupProfile, groupChannelCreateRequest.groupProfile) &&
        Objects.equals(this.permissions, groupChannelCreateRequest.permissions) &&
        Objects.equals(this.groupExtProfile, groupChannelCreateRequest.groupExtProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, name, owner, userIds, groupProfile, permissions, groupExtProfile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupChannelCreateRequest {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    userIds: ").append(toIndentedString(userIds)).append("\n");
    sb.append("    groupProfile: ").append(toIndentedString(groupProfile)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    groupExtProfile: ").append(toIndentedString(groupExtProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelId", "name", "owner", "userIds", "groupProfile", "permissions", "groupExtProfile"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelId", "name", "owner"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GroupChannelCreateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GroupChannelCreateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupChannelCreateRequest is not found in the empty JSON string", GroupChannelCreateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GroupChannelCreateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GroupChannelCreateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GroupChannelCreateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelId").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("userIds") != null && !jsonObj.get("userIds").isJsonNull() && !jsonObj.get("userIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `userIds` to be an array in the JSON string but got `%s`", jsonObj.get("userIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupChannelCreateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupChannelCreateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupChannelCreateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupChannelCreateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupChannelCreateRequest>() {
           @Override
           public void write(JsonWriter out, GroupChannelCreateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupChannelCreateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GroupChannelCreateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GroupChannelCreateRequest
   * @throws IOException if the JSON string is invalid with respect to GroupChannelCreateRequest
   */
  public static GroupChannelCreateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupChannelCreateRequest.class);
  }

  /**
   * Convert an instance of GroupChannelCreateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

