/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * OpenChannelParticipantMuteListAddRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class OpenChannelParticipantMuteListAddRequest {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  @javax.annotation.Nonnull
  private String channelId;

  public static final String SERIALIZED_NAME_PARTICIPANT_IDS = "participantIds";
  @SerializedName(SERIALIZED_NAME_PARTICIPANT_IDS)
  @javax.annotation.Nonnull
  private List<String> participantIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_DURATION_MINUTES = "durationMinutes";
  @SerializedName(SERIALIZED_NAME_DURATION_MINUTES)
  @javax.annotation.Nonnull
  private Integer durationMinutes;

  public static final String SERIALIZED_NAME_EXTRA = "extra";
  @SerializedName(SERIALIZED_NAME_EXTRA)
  @javax.annotation.Nullable
  private String extra;

  public static final String SERIALIZED_NAME_NEED_NOTIFY = "needNotify";
  @SerializedName(SERIALIZED_NAME_NEED_NOTIFY)
  @javax.annotation.Nullable
  private Boolean needNotify;

  public OpenChannelParticipantMuteListAddRequest() {
  }

  public OpenChannelParticipantMuteListAddRequest channelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Get channelId
   * @return channelId
   */
  @javax.annotation.Nonnull
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(@javax.annotation.Nonnull String channelId) {
    this.channelId = channelId;
  }


  public OpenChannelParticipantMuteListAddRequest participantIds(@javax.annotation.Nonnull List<String> participantIds) {
    this.participantIds = participantIds;
    return this;
  }

  public OpenChannelParticipantMuteListAddRequest addParticipantIdsItem(String participantIdsItem) {
    if (this.participantIds == null) {
      this.participantIds = new ArrayList<>();
    }
    this.participantIds.add(participantIdsItem);
    return this;
  }

  /**
   * Get participantIds
   * @return participantIds
   */
  @javax.annotation.Nonnull
  public List<String> getParticipantIds() {
    return participantIds;
  }

  public void setParticipantIds(@javax.annotation.Nonnull List<String> participantIds) {
    this.participantIds = participantIds;
  }


  public OpenChannelParticipantMuteListAddRequest durationMinutes(@javax.annotation.Nonnull Integer durationMinutes) {
    this.durationMinutes = durationMinutes;
    return this;
  }

  /**
   * Get durationMinutes
   * @return durationMinutes
   */
  @javax.annotation.Nonnull
  public Integer getDurationMinutes() {
    return durationMinutes;
  }

  public void setDurationMinutes(@javax.annotation.Nonnull Integer durationMinutes) {
    this.durationMinutes = durationMinutes;
  }


  public OpenChannelParticipantMuteListAddRequest extra(@javax.annotation.Nullable String extra) {
    this.extra = extra;
    return this;
  }

  /**
   * Notification extra payload in JSON string format.
   * @return extra
   */
  @javax.annotation.Nullable
  public String getExtra() {
    return extra;
  }

  public void setExtra(@javax.annotation.Nullable String extra) {
    this.extra = extra;
  }


  public OpenChannelParticipantMuteListAddRequest needNotify(@javax.annotation.Nullable Boolean needNotify) {
    this.needNotify = needNotify;
    return this;
  }

  /**
   * Get needNotify
   * @return needNotify
   */
  @javax.annotation.Nullable
  public Boolean getNeedNotify() {
    return needNotify;
  }

  public void setNeedNotify(@javax.annotation.Nullable Boolean needNotify) {
    this.needNotify = needNotify;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenChannelParticipantMuteListAddRequest openChannelParticipantMuteListAddRequest = (OpenChannelParticipantMuteListAddRequest) o;
    return Objects.equals(this.channelId, openChannelParticipantMuteListAddRequest.channelId) &&
        Objects.equals(this.participantIds, openChannelParticipantMuteListAddRequest.participantIds) &&
        Objects.equals(this.durationMinutes, openChannelParticipantMuteListAddRequest.durationMinutes) &&
        Objects.equals(this.extra, openChannelParticipantMuteListAddRequest.extra) &&
        Objects.equals(this.needNotify, openChannelParticipantMuteListAddRequest.needNotify);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, participantIds, durationMinutes, extra, needNotify);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenChannelParticipantMuteListAddRequest {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    participantIds: ").append(toIndentedString(participantIds)).append("\n");
    sb.append("    durationMinutes: ").append(toIndentedString(durationMinutes)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    needNotify: ").append(toIndentedString(needNotify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("channelId", "participantIds", "durationMinutes", "extra", "needNotify"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("channelId", "participantIds", "durationMinutes"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpenChannelParticipantMuteListAddRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpenChannelParticipantMuteListAddRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenChannelParticipantMuteListAddRequest is not found in the empty JSON string", OpenChannelParticipantMuteListAddRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpenChannelParticipantMuteListAddRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenChannelParticipantMuteListAddRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OpenChannelParticipantMuteListAddRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("channelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("participantIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("participantIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `participantIds` to be an array in the JSON string but got `%s`", jsonObj.get("participantIds").toString()));
      }
      if ((jsonObj.get("extra") != null && !jsonObj.get("extra").isJsonNull()) && !jsonObj.get("extra").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `extra` to be a primitive type in the JSON string but got `%s`", jsonObj.get("extra").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenChannelParticipantMuteListAddRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenChannelParticipantMuteListAddRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenChannelParticipantMuteListAddRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenChannelParticipantMuteListAddRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenChannelParticipantMuteListAddRequest>() {
           @Override
           public void write(JsonWriter out, OpenChannelParticipantMuteListAddRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenChannelParticipantMuteListAddRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpenChannelParticipantMuteListAddRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenChannelParticipantMuteListAddRequest
   * @throws IOException if the JSON string is invalid with respect to OpenChannelParticipantMuteListAddRequest
   */
  public static OpenChannelParticipantMuteListAddRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenChannelParticipantMuteListAddRequest.class);
  }

  /**
   * Convert an instance of OpenChannelParticipantMuteListAddRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

