/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * OpenChannelBannedParticipantItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class OpenChannelBannedParticipantItem {
  public static final String SERIALIZED_NAME_PARTICIPANT_ID = "participantId";
  @SerializedName(SERIALIZED_NAME_PARTICIPANT_ID)
  @javax.annotation.Nullable
  private String participantId;

  public static final String SERIALIZED_NAME_BAN_EXPIRES_AT = "banExpiresAt";
  @SerializedName(SERIALIZED_NAME_BAN_EXPIRES_AT)
  @javax.annotation.Nullable
  private String banExpiresAt;

  public OpenChannelBannedParticipantItem() {
  }

  public OpenChannelBannedParticipantItem participantId(@javax.annotation.Nullable String participantId) {
    this.participantId = participantId;
    return this;
  }

  /**
   * Get participantId
   * @return participantId
   */
  @javax.annotation.Nullable
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(@javax.annotation.Nullable String participantId) {
    this.participantId = participantId;
  }


  public OpenChannelBannedParticipantItem banExpiresAt(@javax.annotation.Nullable String banExpiresAt) {
    this.banExpiresAt = banExpiresAt;
    return this;
  }

  /**
   * Ban expiration time in &#x60;YYYY-MM-DD HH:MM:SS&#x60; format.
   * @return banExpiresAt
   */
  @javax.annotation.Nullable
  public String getBanExpiresAt() {
    return banExpiresAt;
  }

  public void setBanExpiresAt(@javax.annotation.Nullable String banExpiresAt) {
    this.banExpiresAt = banExpiresAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenChannelBannedParticipantItem openChannelBannedParticipantItem = (OpenChannelBannedParticipantItem) o;
    return Objects.equals(this.participantId, openChannelBannedParticipantItem.participantId) &&
        Objects.equals(this.banExpiresAt, openChannelBannedParticipantItem.banExpiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(participantId, banExpiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenChannelBannedParticipantItem {\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("    banExpiresAt: ").append(toIndentedString(banExpiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("participantId", "banExpiresAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpenChannelBannedParticipantItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpenChannelBannedParticipantItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenChannelBannedParticipantItem is not found in the empty JSON string", OpenChannelBannedParticipantItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpenChannelBannedParticipantItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenChannelBannedParticipantItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("participantId") != null && !jsonObj.get("participantId").isJsonNull()) && !jsonObj.get("participantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `participantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("participantId").toString()));
      }
      if ((jsonObj.get("banExpiresAt") != null && !jsonObj.get("banExpiresAt").isJsonNull()) && !jsonObj.get("banExpiresAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `banExpiresAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("banExpiresAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenChannelBannedParticipantItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenChannelBannedParticipantItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenChannelBannedParticipantItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenChannelBannedParticipantItem.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenChannelBannedParticipantItem>() {
           @Override
           public void write(JsonWriter out, OpenChannelBannedParticipantItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenChannelBannedParticipantItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpenChannelBannedParticipantItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenChannelBannedParticipantItem
   * @throws IOException if the JSON string is invalid with respect to OpenChannelBannedParticipantItem
   */
  public static OpenChannelBannedParticipantItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenChannelBannedParticipantItem.class);
  }

  /**
   * Convert an instance of OpenChannelBannedParticipantItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

