/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * OpenChannelMetadataEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class OpenChannelMetadataEntry {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nullable
  private String key;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private String value;

  public static final String SERIALIZED_NAME_METADATA_OWNER_ID = "metadataOwnerId";
  @SerializedName(SERIALIZED_NAME_METADATA_OWNER_ID)
  @javax.annotation.Nullable
  private String metadataOwnerId;

  public static final String SERIALIZED_NAME_SHOULD_AUTO_DELETE = "shouldAutoDelete";
  @SerializedName(SERIALIZED_NAME_SHOULD_AUTO_DELETE)
  @javax.annotation.Nullable
  private Integer shouldAutoDelete;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private Long updatedAt;

  public OpenChannelMetadataEntry() {
  }

  public OpenChannelMetadataEntry key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nullable
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public OpenChannelMetadataEntry value(@javax.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  public OpenChannelMetadataEntry metadataOwnerId(@javax.annotation.Nullable String metadataOwnerId) {
    this.metadataOwnerId = metadataOwnerId;
    return this;
  }

  /**
   * KV entry owner; serializes as &#x60;metadataOwnerId&#x60; from the source map key &#x60;userId&#x60; (&#x60;OpenChannelMetadataListResult.MetadataItem&#x60;).
   * @return metadataOwnerId
   */
  @javax.annotation.Nullable
  public String getMetadataOwnerId() {
    return metadataOwnerId;
  }

  public void setMetadataOwnerId(@javax.annotation.Nullable String metadataOwnerId) {
    this.metadataOwnerId = metadataOwnerId;
  }


  public OpenChannelMetadataEntry shouldAutoDelete(@javax.annotation.Nullable Integer shouldAutoDelete) {
    this.shouldAutoDelete = shouldAutoDelete;
    return this;
  }

  /**
   * Parsed from source &#x60;autoDelete&#x60; string. &#x60;1&#x60; enables auto-delete and &#x60;0&#x60; disables it.
   * @return shouldAutoDelete
   */
  @javax.annotation.Nullable
  public Integer getShouldAutoDelete() {
    return shouldAutoDelete;
  }

  public void setShouldAutoDelete(@javax.annotation.Nullable Integer shouldAutoDelete) {
    this.shouldAutoDelete = shouldAutoDelete;
  }


  public OpenChannelMetadataEntry updatedAt(@javax.annotation.Nullable Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Parsed from source &#x60;lastSetTime&#x60; (milliseconds).
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public Long getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable Long updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenChannelMetadataEntry openChannelMetadataEntry = (OpenChannelMetadataEntry) o;
    return Objects.equals(this.key, openChannelMetadataEntry.key) &&
        Objects.equals(this.value, openChannelMetadataEntry.value) &&
        Objects.equals(this.metadataOwnerId, openChannelMetadataEntry.metadataOwnerId) &&
        Objects.equals(this.shouldAutoDelete, openChannelMetadataEntry.shouldAutoDelete) &&
        Objects.equals(this.updatedAt, openChannelMetadataEntry.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, metadataOwnerId, shouldAutoDelete, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenChannelMetadataEntry {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    metadataOwnerId: ").append(toIndentedString(metadataOwnerId)).append("\n");
    sb.append("    shouldAutoDelete: ").append(toIndentedString(shouldAutoDelete)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("key", "value", "metadataOwnerId", "shouldAutoDelete", "updatedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpenChannelMetadataEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpenChannelMetadataEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenChannelMetadataEntry is not found in the empty JSON string", OpenChannelMetadataEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpenChannelMetadataEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenChannelMetadataEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("key") != null && !jsonObj.get("key").isJsonNull()) && !jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("metadataOwnerId") != null && !jsonObj.get("metadataOwnerId").isJsonNull()) && !jsonObj.get("metadataOwnerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `metadataOwnerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("metadataOwnerId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenChannelMetadataEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenChannelMetadataEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenChannelMetadataEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenChannelMetadataEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenChannelMetadataEntry>() {
           @Override
           public void write(JsonWriter out, OpenChannelMetadataEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenChannelMetadataEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpenChannelMetadataEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenChannelMetadataEntry
   * @throws IOException if the JSON string is invalid with respect to OpenChannelMetadataEntry
   */
  public static OpenChannelMetadataEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenChannelMetadataEntry.class);
  }

  /**
   * Convert an instance of OpenChannelMetadataEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

