/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.nexconn.JSON;

/**
 * SystemChannelPushNotification
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SystemChannelPushNotification {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_FORCE_SHOW_PUSH_CONTENT = "forceShowPushContent";
  @SerializedName(SERIALIZED_NAME_FORCE_SHOW_PUSH_CONTENT)
  @javax.annotation.Nullable
  private Integer forceShowPushContent;

  public static final String SERIALIZED_NAME_ALERT = "alert";
  @SerializedName(SERIALIZED_NAME_ALERT)
  @javax.annotation.Nullable
  private String alert;

  public static final String SERIALIZED_NAME_IOS = "ios";
  @SerializedName(SERIALIZED_NAME_IOS)
  @javax.annotation.Nullable
  private Map<String, Object> ios = new HashMap<>();

  public static final String SERIALIZED_NAME_ANDROID = "android";
  @SerializedName(SERIALIZED_NAME_ANDROID)
  @javax.annotation.Nullable
  private Map<String, Object> android = new HashMap<>();

  public static final String SERIALIZED_NAME_HARMONY_O_S = "harmonyOS";
  @SerializedName(SERIALIZED_NAME_HARMONY_O_S)
  @javax.annotation.Nullable
  private Map<String, Object> harmonyOS = new HashMap<>();

  public SystemChannelPushNotification() {
  }

  public SystemChannelPushNotification title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public SystemChannelPushNotification forceShowPushContent(@javax.annotation.Nullable Integer forceShowPushContent) {
    this.forceShowPushContent = forceShowPushContent;
    return this;
  }

  /**
   * Get forceShowPushContent
   * @return forceShowPushContent
   */
  @javax.annotation.Nullable
  public Integer getForceShowPushContent() {
    return forceShowPushContent;
  }

  public void setForceShowPushContent(@javax.annotation.Nullable Integer forceShowPushContent) {
    this.forceShowPushContent = forceShowPushContent;
  }


  public SystemChannelPushNotification alert(@javax.annotation.Nullable String alert) {
    this.alert = alert;
    return this;
  }

  /**
   * Get alert
   * @return alert
   */
  @javax.annotation.Nullable
  public String getAlert() {
    return alert;
  }

  public void setAlert(@javax.annotation.Nullable String alert) {
    this.alert = alert;
  }


  public SystemChannelPushNotification ios(@javax.annotation.Nullable Map<String, Object> ios) {
    this.ios = ios;
    return this;
  }

  public SystemChannelPushNotification putIosItem(String key, Object iosItem) {
    if (this.ios == null) {
      this.ios = new HashMap<>();
    }
    this.ios.put(key, iosItem);
    return this;
  }

  /**
   * Get ios
   * @return ios
   */
  @javax.annotation.Nullable
  public Map<String, Object> getIos() {
    return ios;
  }

  public void setIos(@javax.annotation.Nullable Map<String, Object> ios) {
    this.ios = ios;
  }


  public SystemChannelPushNotification android(@javax.annotation.Nullable Map<String, Object> android) {
    this.android = android;
    return this;
  }

  public SystemChannelPushNotification putAndroidItem(String key, Object androidItem) {
    if (this.android == null) {
      this.android = new HashMap<>();
    }
    this.android.put(key, androidItem);
    return this;
  }

  /**
   * Get android
   * @return android
   */
  @javax.annotation.Nullable
  public Map<String, Object> getAndroid() {
    return android;
  }

  public void setAndroid(@javax.annotation.Nullable Map<String, Object> android) {
    this.android = android;
  }


  public SystemChannelPushNotification harmonyOS(@javax.annotation.Nullable Map<String, Object> harmonyOS) {
    this.harmonyOS = harmonyOS;
    return this;
  }

  public SystemChannelPushNotification putHarmonyOSItem(String key, Object harmonyOSItem) {
    if (this.harmonyOS == null) {
      this.harmonyOS = new HashMap<>();
    }
    this.harmonyOS.put(key, harmonyOSItem);
    return this;
  }

  /**
   * Get harmonyOS
   * @return harmonyOS
   */
  @javax.annotation.Nullable
  public Map<String, Object> getHarmonyOS() {
    return harmonyOS;
  }

  public void setHarmonyOS(@javax.annotation.Nullable Map<String, Object> harmonyOS) {
    this.harmonyOS = harmonyOS;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemChannelPushNotification systemChannelPushNotification = (SystemChannelPushNotification) o;
    return Objects.equals(this.title, systemChannelPushNotification.title) &&
        Objects.equals(this.forceShowPushContent, systemChannelPushNotification.forceShowPushContent) &&
        Objects.equals(this.alert, systemChannelPushNotification.alert) &&
        Objects.equals(this.ios, systemChannelPushNotification.ios) &&
        Objects.equals(this.android, systemChannelPushNotification.android) &&
        Objects.equals(this.harmonyOS, systemChannelPushNotification.harmonyOS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, forceShowPushContent, alert, ios, android, harmonyOS);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemChannelPushNotification {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    forceShowPushContent: ").append(toIndentedString(forceShowPushContent)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    ios: ").append(toIndentedString(ios)).append("\n");
    sb.append("    android: ").append(toIndentedString(android)).append("\n");
    sb.append("    harmonyOS: ").append(toIndentedString(harmonyOS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("title", "forceShowPushContent", "alert", "ios", "android", "harmonyOS"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SystemChannelPushNotification
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SystemChannelPushNotification.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SystemChannelPushNotification is not found in the empty JSON string", SystemChannelPushNotification.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SystemChannelPushNotification.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SystemChannelPushNotification` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("alert") != null && !jsonObj.get("alert").isJsonNull()) && !jsonObj.get("alert").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alert` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alert").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SystemChannelPushNotification.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SystemChannelPushNotification' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SystemChannelPushNotification> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SystemChannelPushNotification.class));

       return (TypeAdapter<T>) new TypeAdapter<SystemChannelPushNotification>() {
           @Override
           public void write(JsonWriter out, SystemChannelPushNotification value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SystemChannelPushNotification read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SystemChannelPushNotification given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SystemChannelPushNotification
   * @throws IOException if the JSON string is invalid with respect to SystemChannelPushNotification
   */
  public static SystemChannelPushNotification fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SystemChannelPushNotification.class);
  }

  /**
   * Convert an instance of SystemChannelPushNotification to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

