/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiException;
import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.CommunityChannelAllowedSenderListGetRequest;
import ai.nexconn.model.CommunityChannelAllowedSenderListGetResponse;
import ai.nexconn.model.CommunityChannelAllowedSenderListUpdateRequest;
import ai.nexconn.model.CommunityChannelFreezeListGetRequest;
import ai.nexconn.model.CommunityChannelFreezeListGetResponse;
import ai.nexconn.model.CommunityChannelFreezeListSetRequest;
import ai.nexconn.model.CommunityChannelMuteListAddRequest;
import ai.nexconn.model.CommunityChannelMuteListGetRequest;
import ai.nexconn.model.CommunityChannelMuteListGetResponse;
import ai.nexconn.model.CommunityChannelMuteListRemoveRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommunityChannelModerationApi
 */
@Disabled
public class CommunityChannelModerationApiTest {

    private final CommunityChannelModerationApi api = new CommunityChannelModerationApi();

    /**
     * Add community channel allowed sender list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCommunityChannelAllowedSenderListTest() throws ApiException {
        CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest = null;
        CodeOnlyResponse response = api.addCommunityChannelAllowedSenderList(communityChannelAllowedSenderListUpdateRequest);
        // TODO: test validations
    }

    /**
     * Add community-channel muted users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCommunityChannelMutedUsersTest() throws ApiException {
        CommunityChannelMuteListAddRequest communityChannelMuteListAddRequest = null;
        CodeOnlyResponse response = api.addCommunityChannelMutedUsers(communityChannelMuteListAddRequest);
        // TODO: test validations
    }

    /**
     * Get community channel freeze status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCommunityChannelFreezeListTest() throws ApiException {
        CommunityChannelFreezeListGetRequest communityChannelFreezeListGetRequest = null;
        CommunityChannelFreezeListGetResponse response = api.getCommunityChannelFreezeList(communityChannelFreezeListGetRequest);
        // TODO: test validations
    }

    /**
     * List community channel allowed sender list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCommunityChannelAllowedSenderListTest() throws ApiException {
        CommunityChannelAllowedSenderListGetRequest communityChannelAllowedSenderListGetRequest = null;
        CommunityChannelAllowedSenderListGetResponse response = api.listCommunityChannelAllowedSenderList(communityChannelAllowedSenderListGetRequest);
        // TODO: test validations
    }

    /**
     * List community-channel muted users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCommunityChannelMutedUsersTest() throws ApiException {
        CommunityChannelMuteListGetRequest communityChannelMuteListGetRequest = null;
        CommunityChannelMuteListGetResponse response = api.listCommunityChannelMutedUsers(communityChannelMuteListGetRequest);
        // TODO: test validations
    }

    /**
     * Remove community channel allowed sender list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCommunityChannelAllowedSenderListTest() throws ApiException {
        CommunityChannelAllowedSenderListUpdateRequest communityChannelAllowedSenderListUpdateRequest = null;
        CodeOnlyResponse response = api.removeCommunityChannelAllowedSenderList(communityChannelAllowedSenderListUpdateRequest);
        // TODO: test validations
    }

    /**
     * Remove community-channel muted users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCommunityChannelMutedUsersTest() throws ApiException {
        CommunityChannelMuteListRemoveRequest communityChannelMuteListRemoveRequest = null;
        CodeOnlyResponse response = api.removeCommunityChannelMutedUsers(communityChannelMuteListRemoveRequest);
        // TODO: test validations
    }

    /**
     * Set community channel freeze list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setCommunityChannelFreezeListTest() throws ApiException {
        CommunityChannelFreezeListSetRequest communityChannelFreezeListSetRequest = null;
        CodeOnlyResponse response = api.setCommunityChannelFreezeList(communityChannelFreezeListSetRequest);
        // TODO: test validations
    }

}
