/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiException;
import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.OpenChannelMetadataBatchGetRequest;
import ai.nexconn.model.OpenChannelMetadataBatchGetResponse;
import ai.nexconn.model.OpenChannelMetadataBatchRemoveRequest;
import ai.nexconn.model.OpenChannelMetadataBatchSetRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenChannelMetadataApi
 */
@Disabled
public class OpenChannelMetadataApiTest {

    private final OpenChannelMetadataApi api = new OpenChannelMetadataApi();

    /**
     * Query metadata
     *
     * Rate limit: 100/sec.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchGetOpenChannelMetadataTest() throws ApiException {
        OpenChannelMetadataBatchGetRequest openChannelMetadataBatchGetRequest = null;
        OpenChannelMetadataBatchGetResponse response = api.batchGetOpenChannelMetadata(openChannelMetadataBatchGetRequest);
        // TODO: test validations
    }

    /**
     * Batch delete metadata
     *
     * Rate limit: 100 attrs/sec (shared).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchRemoveOpenChannelMetadataTest() throws ApiException {
        OpenChannelMetadataBatchRemoveRequest openChannelMetadataBatchRemoveRequest = null;
        CodeOnlyResponse response = api.batchRemoveOpenChannelMetadata(openChannelMetadataBatchRemoveRequest);
        // TODO: test validations
    }

    /**
     * Batch set metadata
     *
     * Rate limit: 100 attrs/sec (shared).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchSetOpenChannelMetadataTest() throws ApiException {
        OpenChannelMetadataBatchSetRequest openChannelMetadataBatchSetRequest = null;
        CodeOnlyResponse response = api.batchSetOpenChannelMetadata(openChannelMetadataBatchSetRequest);
        // TODO: test validations
    }

}
