/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiException;
import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.OpenChannelMessageTypeListResponse;
import ai.nexconn.model.OpenChannelParticipantIdsRequest;
import ai.nexconn.model.OpenChannelParticipantIdsResponse;
import ai.nexconn.model.OpenChannelParticipantListByChannelRequest;
import ai.nexconn.model.OpenChannelPriorityMessageTypeListRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenChannelPriorityControlsApi
 */
@Disabled
public class OpenChannelPriorityControlsApiTest {

    private final OpenChannelPriorityControlsApi api = new OpenChannelPriorityControlsApi();

    /**
     * Add priority message types
     *
     * Rate limit: 100/sec.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addOpenChannelPriorityMessageTypeListTest() throws ApiException {
        OpenChannelPriorityMessageTypeListRequest openChannelPriorityMessageTypeListRequest = null;
        CodeOnlyResponse response = api.addOpenChannelPriorityMessageTypeList(openChannelPriorityMessageTypeListRequest);
        // TODO: test validations
    }

    /**
     * Add priority senders
     *
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/open-channel/participant/priority-sender-list/add&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addOpenChannelPrioritySenderListTest() throws ApiException {
        OpenChannelParticipantIdsRequest openChannelParticipantIdsRequest = null;
        CodeOnlyResponse response = api.addOpenChannelPrioritySenderList(openChannelParticipantIdsRequest);
        // TODO: test validations
    }

    /**
     * Query priority message types
     *
     * Rate limit: 100/sec.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOpenChannelPriorityMessageTypeListTest() throws ApiException {
        Object body = null;
        OpenChannelMessageTypeListResponse response = api.getOpenChannelPriorityMessageTypeList(body);
        // TODO: test validations
    }

    /**
     * Query priority senders
     *
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/open-channel/participant/priority-sender-list/get&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOpenChannelPrioritySenderListTest() throws ApiException {
        OpenChannelParticipantListByChannelRequest openChannelParticipantListByChannelRequest = null;
        OpenChannelParticipantIdsResponse response = api.getOpenChannelPrioritySenderList(openChannelParticipantListByChannelRequest);
        // TODO: test validations
    }

    /**
     * Remove priority message types
     *
     * Rate limit: 100/sec.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeOpenChannelPriorityMessageTypeListTest() throws ApiException {
        OpenChannelPriorityMessageTypeListRequest openChannelPriorityMessageTypeListRequest = null;
        CodeOnlyResponse response = api.removeOpenChannelPriorityMessageTypeList(openChannelPriorityMessageTypeListRequest);
        // TODO: test validations
    }

    /**
     * Remove priority senders
     *
     * Rate limit: 100/sec. The public endpoint list currently publishes this capability as &#x60;/v4/open-channel/participant/priority-sender-list/remove&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeOpenChannelPrioritySenderListTest() throws ApiException {
        OpenChannelParticipantIdsRequest openChannelParticipantIdsRequest = null;
        CodeOnlyResponse response = api.removeOpenChannelPrioritySenderList(openChannelParticipantIdsRequest);
        // TODO: test validations
    }

}
