/*
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.nexconn.api;

import ai.nexconn.ApiException;
import ai.nexconn.model.CodeOnlyResponse;
import ai.nexconn.model.UserIdsMax20Request;
import ai.nexconn.model.UserProfileBatchGetResponse;
import ai.nexconn.model.UserProfileListRequest;
import ai.nexconn.model.UserProfileListResponse;
import ai.nexconn.model.UserProfileSetRequest;
import ai.nexconn.model.UserProfileSetResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserProfileHostingApi
 */
@Disabled
public class UserProfileHostingApiTest {

    private final UserProfileHostingApi api = new UserProfileHostingApi();

    /**
     * Batch get user profiles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchGetUserProfilesTest() throws ApiException {
        UserIdsMax20Request userIdsMax20Request = null;
        UserProfileBatchGetResponse response = api.batchGetUserProfiles(userIdsMax20Request);
        // TODO: test validations
    }

    /**
     * Clear user profiles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserProfilesTest() throws ApiException {
        UserIdsMax20Request userIdsMax20Request = null;
        CodeOnlyResponse response = api.deleteUserProfiles(userIdsMax20Request);
        // TODO: test validations
    }

    /**
     * List user profiles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUserProfilesTest() throws ApiException {
        UserProfileListRequest userProfileListRequest = null;
        UserProfileListResponse response = api.listUserProfiles(userProfileListRequest);
        // TODO: test validations
    }

    /**
     * Set user profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setUserProfileTest() throws ApiException {
        UserProfileSetRequest userProfileSetRequest = null;
        UserProfileSetResponse response = api.setUserProfile(userProfileSetRequest);
        // TODO: test validations
    }

}
